local util = require("ipparse.lib.util")
local test, summary
test, summary = util.test, util.summary
local hex_to_bin
hex_to_bin = require("ipparse.lib.hkdf").hex_to_bin
local bin2hex
bin2hex = function(s)
  return s:gsub(".", function(c)
    return string.format("%02x", c:byte())
  end)
end
local ok, b = pcall(require, "ipparse.lib.crypto.backend.ffi_wolfssl")
if not (ok) then
  test("ffi_wolfssl: backend not available (skipped)", function()
    return true
  end)
  summary("lib.crypto.ffi_wolfssl")
  return 
end
test("ffi_wolfssl: GCM encrypt empty plaintext (NIST)", function()
  local key = string.rep("\x00", 16)
  local nonce = string.rep("\x00", 12)
  local ct = b.aes_128_gcm_encrypt(key, nonce, "", "")
  assert(#ct == 16, "ciphertext should be 16-byte tag only")
  return assert(bin2hex(ct) == "58e2fccefa7e3061367f1d57a4e7455a", "tag mismatch: " .. tostring(bin2hex(ct)))
end)
test("ffi_wolfssl: GCM decrypt empty plaintext (NIST)", function()
  local key = string.rep("\x00", 16)
  local nonce = string.rep("\x00", 12)
  local tag = hex_to_bin("58e2fccefa7e3061367f1d57a4e7455a")
  local pt, err = b.aes_128_gcm_decrypt(key, nonce, tag, "")
  return assert(pt == "", "plaintext should be empty, got: " .. tostring(tostring(err)))
end)
test("ffi_wolfssl: GCM encrypt/decrypt round-trip", function()
  local key = string.rep("\x42", 16)
  local nonce = string.rep("\x00", 12)
  local plain = "hello, wolfssl!!"
  local ct = b.aes_128_gcm_encrypt(key, nonce, plain, "aad-data")
  local pt, err = b.aes_128_gcm_decrypt(key, nonce, ct, "aad-data")
  return assert(pt == plain, "round-trip failed: " .. tostring(tostring(err)))
end)
test("ffi_wolfssl: GCM decrypt fails on bad tag", function()
  local key = string.rep("\x00", 16)
  local nonce = string.rep("\x00", 12)
  local tag = string.rep("\xff", 16)
  local pt, err = b.aes_128_gcm_decrypt(key, nonce, tag, "")
  assert(pt == nil, "should return nil on bad tag")
  return assert(err ~= nil, "should return error message")
end)
test("ffi_wolfssl: GCM decrypt fails on tampered AAD", function()
  local key = string.rep("\x42", 16)
  local nonce = string.rep("\x00", 12)
  local ct = b.aes_128_gcm_encrypt(key, nonce, "test data...!!!!", "correct-aad")
  local pt, err = b.aes_128_gcm_decrypt(key, nonce, ct, "wrong-aad")
  return assert(pt == nil, "should fail with wrong AAD")
end)
test("ffi_wolfssl: ECB RFC 9001 §A.2 header-protection mask", function()
  local hp = hex_to_bin("9f50449e04a0e810283a1e9933adedd2")
  local sample = hex_to_bin("d1b1c98dd7689fb8ec11d242b123dc9b")
  local mask = b.aes_128_ecb_block(hp, sample)
  assert(#mask == 16, "mask must be 16 bytes")
  return assert(bin2hex(mask):sub(1, 10) == "437b9aec36", "first 5 bytes mismatch: " .. tostring(bin2hex(mask):sub(1, 10)))
end)
test("ffi_wolfssl: ECB known NIST vector (key=0^16, block=0^16)", function()
  local key = string.rep("\x00", 16)
  local block = string.rep("\x00", 16)
  local out = b.aes_128_ecb_block(key, block)
  return assert(bin2hex(out) == "66e94bd4ef8a2c3b884cfa59ca342b2e", "NIST ECB mismatch: " .. tostring(bin2hex(out)))
end)
test("ffi_wolfssl: construct_nonce pn=0 returns iv unchanged", function()
  local iv = hex_to_bin("fa044b2f42a3fd3b46fb255c")
  return assert(b.construct_nonce(iv, 0) == iv, "nonce should equal iv when pn=0")
end)
test("ffi_wolfssl: construct_nonce pn=1 XORs last byte", function()
  local iv = hex_to_bin("fa044b2f42a3fd3b46fb255c")
  local nonce = b.construct_nonce(iv, 1)
  assert(nonce:sub(1, 11) == iv:sub(1, 11), "first 11 bytes unchanged")
  return assert(nonce:byte(12) == 0x5d, "last byte 0x5c XOR 0x01 = 0x5d")
end)
test("ffi_wolfssl: construct_nonce pn=0x0102 XORs last two bytes", function()
  local iv = string.rep("\x00", 12)
  local nonce = b.construct_nonce(iv, 0x0102)
  assert(nonce:byte(11) == 0x01, "byte 11 should be 0x01")
  return assert(nonce:byte(12) == 0x02, "byte 12 should be 0x02")
end)
return summary("lib.crypto.ffi_wolfssl")
