local util = require("ipparse.lib.util")
local test
test = util.test
local parse_frame, iter_frames, validate_frames, encode_varint
do
  local _obj_0 = require("ipparse.l4.quic.frames")
  parse_frame, iter_frames, validate_frames, encode_varint = _obj_0.parse_frame, _obj_0.iter_frames, _obj_0.validate_frames, _obj_0.encode_varint
end
test("frame: PADDING parsed", function()
  local f, off = parse_frame("\x00", 1)
  return assert(f.type == 0x00 and f.name == "PADDING", "expected PADDING")
end)
test("frame: PING parsed", function()
  local f, off = parse_frame("\x01", 1)
  return assert(f.type == 0x01 and f.name == "PING", "expected PING")
end)
test("frame: ACK minimal parsed", function()
  local data = "\x02\x00\x00\x00\x00"
  local f, _ = parse_frame(data, 1)
  assert(f.type == 0x02 and f.name == "ACK")
  return assert(f.largest_acked == 0)
end)
test("frame: CRYPTO frame parsed", function()
  local payload = "hello"
  local data = "\x06" .. encode_varint(0) .. encode_varint(#payload) .. payload
  local f, _ = parse_frame(data, 1)
  assert(f.type == 0x06 and f.name == "CRYPTO")
  assert(f.data == payload, "crypto data mismatch")
  return assert(f.length == 5)
end)
test("frame: STREAM frame parsed", function()
  local payload = "world"
  local data = "\x0E" .. encode_varint(1) .. encode_varint(0) .. encode_varint(#payload) .. payload
  local f, _ = parse_frame(data, 1)
  assert(f.type == 0x0E and f.name == "STREAM")
  assert(f.id == 1)
  return assert(f.data == payload)
end)
test("frame: RESET_STREAM parsed", function()
  local data = "\x04" .. encode_varint(3) .. encode_varint(0) .. encode_varint(100)
  local f, _ = parse_frame(data, 1)
  assert(f.type == 0x04 and f.name == "RESET_STREAM")
  return assert(f.stream_id == 3 and f.final_size == 100)
end)
test("frame: STOP_SENDING parsed", function()
  local data = "\x05" .. encode_varint(7) .. encode_varint(42)
  local f, _ = parse_frame(data, 1)
  assert(f.type == 0x05 and f.name == "STOP_SENDING")
  return assert(f.stream_id == 7 and f.app_error_code == 42)
end)
test("frame: MAX_DATA parsed", function()
  local data = "\x10" .. encode_varint(1000)
  local f, _ = parse_frame(data, 1)
  assert(f.type == 0x10 and f.name == "MAX_DATA")
  return assert(f.maximum_data == 1000)
end)
test("frame: MAX_STREAM_DATA parsed", function()
  local data = "\x11" .. encode_varint(2) .. encode_varint(2000)
  local f, _ = parse_frame(data, 1)
  assert(f.type == 0x11 and f.name == "MAX_STREAM_DATA")
  return assert(f.stream_id == 2 and f.maximum_stream_data == 2000)
end)
test("frame: MAX_STREAMS_BIDI parsed", function()
  local data = "\x12" .. encode_varint(10)
  local f, _ = parse_frame(data, 1)
  assert(f.type == 0x12 and f.name == "MAX_STREAMS_BIDI")
  return assert(f.maximum_streams == 10)
end)
test("frame: DATA_BLOCKED parsed", function()
  local data = "\x14" .. encode_varint(500)
  local f, _ = parse_frame(data, 1)
  assert(f.type == 0x14 and f.name == "DATA_BLOCKED")
  return assert(f.maximum_data == 500)
end)
test("frame: NEW_CONNECTION_ID parsed", function()
  local cid = "\xAA\xBB\xCC\xDD\xEE\xFF\x11\x22"
  local rst = string.rep("\x00", 16)
  local data = "\x18" .. encode_varint(1) .. encode_varint(0) .. "\x08" .. cid .. rst
  local f, _ = parse_frame(data, 1)
  assert(f.type == 0x18 and f.name == "NEW_CONNECTION_ID")
  assert(f.sequence_number == 1)
  return assert(f.connection_id == cid)
end)
test("frame: RETIRE_CONNECTION_ID parsed", function()
  local data = "\x19" .. encode_varint(5)
  local f, _ = parse_frame(data, 1)
  assert(f.type == 0x19 and f.name == "RETIRE_CONNECTION_ID")
  return assert(f.sequence_number == 5)
end)
test("frame: PATH_CHALLENGE parsed", function()
  local data = "\x1a" .. string.rep("\xAB", 8)
  local f, _ = parse_frame(data, 1)
  assert(f.type == 0x1a and f.name == "PATH_CHALLENGE")
  return assert(#f.data == 8)
end)
test("frame: PATH_RESPONSE parsed", function()
  local data = "\x1b" .. string.rep("\xCD", 8)
  local f, _ = parse_frame(data, 1)
  return assert(f.type == 0x1b and f.name == "PATH_RESPONSE")
end)
test("frame: CONNECTION_CLOSE parsed", function()
  local reason = "test error"
  local data = "\x1c" .. encode_varint(0) .. encode_varint(0) .. encode_varint(#reason) .. reason
  local f, _ = parse_frame(data, 1)
  assert(f.type == 0x1c and f.name == "CONNECTION_CLOSE")
  return assert(f.reason_phrase == reason)
end)
test("frame: HANDSHAKE_DONE parsed", function()
  local f, _ = parse_frame("\x1e", 1)
  return assert(f.type == 0x1e and f.name == "HANDSHAKE_DONE")
end)
test("frame: CRYPTO truncated payload returns nil", function()
  local data = "\x06\x00\x05\xaa"
  local f, _, err = parse_frame(data, 1)
  assert(f == nil, "expected parse failure")
  return assert(err and err:match("CRYPTO"), "expected CRYPTO error, got " .. tostring(err))
end)
test("frame: PATH_CHALLENGE truncated returns nil", function()
  local f, _, err = parse_frame("\x1a\xaa", 1)
  assert(f == nil, "expected parse failure")
  return assert(err and err:match("PATH_CHALLENGE"), "expected PATH_CHALLENGE error, got " .. tostring(err))
end)
test("frame: iter_frames over two frames", function()
  local data = "\x01\x01"
  local count = 0
  for f in iter_frames(data) do
    count = count + 1
  end
  return assert(count == 2, "expected 2 frames, got " .. tostring(count))
end)
test("frame: validate_frames succeeds on valid data", function()
  local data = "\x01\x01"
  local ok, msg = validate_frames(data)
  return assert(ok == true, "expected valid, got: " .. tostring(msg))
end)
test("frame: validate_frames fails on malformed data", function()
  local data = "\x06\x00\x05\xaa"
  local ok, msg = validate_frames(data)
  assert(ok == false, "expected invalid data")
  return assert(msg and msg:match("CRYPTO"), "expected CRYPTO validation error, got " .. tostring(msg))
end)
test("frame: UNKNOWN frame does not get stuck", function()
  local data = "\x20\x01"
  local f1, off1 = parse_frame(data, 1)
  assert(f1.name == "UNKNOWN", "expected UNKNOWN, got " .. tostring(f1.name))
  local f2, off2 = parse_frame(data, off1)
  return assert(f2.name == "PING", "expected PING after UNKNOWN, got " .. tostring(f2.name))
end)
return util.summary("frames")
