local util = require("ipparse.lib.util")
local test
test = util.test
local parse_varint, encode_varint
do
  local _obj_0 = require("ipparse.l4.quic.frames")
  parse_varint, encode_varint = _obj_0.parse_varint, _obj_0.encode_varint
end
test("varint: parse 1-byte value 0", function()
  local v, off = parse_varint("\x00", 1)
  return assert(v == 0 and off == 2, "expected 0, got " .. tostring(v))
end)
test("varint: parse 1-byte value 63", function()
  local v, off = parse_varint("\x3F", 1)
  return assert(v == 63 and off == 2, "expected 63, got " .. tostring(v))
end)
test("varint: parse 2-byte value 64", function()
  local v, off = parse_varint("\x40\x40", 1)
  return assert(v == 64 and off == 3, "expected 64, got " .. tostring(v))
end)
test("varint: parse 2-byte value 16383", function()
  local v, off = parse_varint("\x7F\xFF", 1)
  return assert(v == 16383 and off == 3, "expected 16383, got " .. tostring(v))
end)
test("varint: parse 4-byte value 16384", function()
  local v, off = parse_varint("\x80\x00\x40\x00", 1)
  return assert(v == 16384 and off == 5, "expected 16384, got " .. tostring(v))
end)
test("varint: encode 0", function()
  return assert(encode_varint(0) == "\x00")
end)
test("varint: encode 63", function()
  return assert(encode_varint(63) == "\x3F")
end)
test("varint: encode 64", function()
  return assert(encode_varint(64) == "\x40\x40")
end)
test("varint: encode 16383", function()
  return assert(encode_varint(16383) == "\x7F\xFF")
end)
test("varint: round-trip 500", function()
  local encoded = encode_varint(500)
  local v, _ = parse_varint(encoded, 1)
  return assert(v == 500, "round-trip 500 failed: got " .. tostring(v))
end)
test("varint: round-trip 70000", function()
  local encoded = encode_varint(70000)
  local v, _ = parse_varint(encoded, 1)
  return assert(v == 70000, "round-trip 70000 failed: got " .. tostring(v))
end)
test("varint: round-trip 8-byte value", function()
  local value = 4886718345
  local encoded = encode_varint(value)
  local v, _ = parse_varint(encoded, 1)
  return assert(v == value, "round-trip 8-byte value failed: got " .. tostring(v))
end)
test("varint: truncated 8-byte returns nil", function()
  local v, off = parse_varint("\xC0\x00", 1)
  return assert(v == nil and off == 1, "expected nil with unchanged offset")
end)
test("varint: parse at non-1 offset", function()
  local data = "\xFF" .. "\x3F"
  local v, off = parse_varint(data, 2)
  return assert(v == 63 and off == 3)
end)
return util.summary("varint")
