local crypto = require("ipparse.l4.quic.crypto")
local bin2hex, hex2bin
do
  local _obj_0 = require("ipparse.init")
  bin2hex, hex2bin = _obj_0.bin2hex, _obj_0.hex2bin
end
print("=== Testing QUIC Cryptography ===")
print("")
print("=== Initial Secret Derivation ===")
local connection_id = hex2bin("133a971cdef32a97")
print("Connection ID: " .. tostring(bin2hex(connection_id)))
local client_secret, server_secret = crypto.derive_initial_secrets(connection_id)
print("✓ Initial secrets derived")
print("  Client secret: " .. tostring(bin2hex(client_secret)))
print("  Server secret: " .. tostring(bin2hex(server_secret)))
print("")
print("=== Packet Protection Keys ===")
local client_key, client_iv, client_hp_key = crypto.derive_packet_protection_keys(client_secret)
print("✓ Client packet protection keys derived")
print("  Packet key: " .. tostring(bin2hex(client_key)))
print("  Packet IV: " .. tostring(bin2hex(client_iv)))
print("  Header protection key: " .. tostring(bin2hex(client_hp_key)))
print("")
print("=== Header Protection Mask ===")
local sample = hex2bin("0123456789abcdef0123456789abcdef")
local mask = crypto.generate_header_mask(client_hp_key, sample)
print("✓ Header protection mask generated")
print("  Sample: " .. tostring(bin2hex(sample)))
print("  Mask: " .. tostring(bin2hex(mask)))
print("")
print("=== Packet Number Recovery ===")
local truncated_pn = 0x42
local expected_pn = 0x100
local pn_nbits = 8
local recovered_pn = crypto.recover_packet_number(truncated_pn, expected_pn, pn_nbits)
print("✓ Packet number recovery test")
print("  Truncated PN: 0x" .. tostring(string.format("%02x", truncated_pn)))
print("  Expected PN: 0x" .. tostring(string.format("%02x", expected_pn)))
print("  Recovered PN: 0x" .. tostring(string.format("%02x", recovered_pn)))
print("")
print("=== Header Protection Removal ===")
local protected_header = hex2bin("c0000001" .. string.rep("\x42", 4))
print("Protected header: " .. tostring(bin2hex(protected_header)))
local unprotected_header, packet_number = crypto.remove_header_protection(protected_header, client_hp_key, sample, true)
print("✓ Header protection removed")
print("  Unprotected header: " .. tostring(bin2hex(unprotected_header)))
print("  Extracted packet number: " .. tostring(packet_number))
print("")
print("=== Complete Packet Number Recovery ===")
local final_header, final_pn = crypto.recover_quic_packet_number(protected_header, client_hp_key, sample, 0, true)
print("✓ Complete packet number recovery")
print("  Final header: " .. tostring(bin2hex(final_header)))
print("  Final packet number: " .. tostring(final_pn))
print("")
print("=== QUIC Crypto Test Summary ===")
print("✓ Initial secret derivation working")
print("✓ Packet protection key derivation working")
print("✓ Header protection mask generation working")
print("✓ Packet number recovery working")
print("✓ Header protection removal working")
print("")
return print("Phase 4 (Packet Number Protection/Recovery) implementation complete!")
