-- tools/classifier/descriptions.moon
-- Brève description (anglais) de chaque catégorie de listes, injectée dans le
-- prompt de classification pour lever les ambiguïtés (cf. classifier.moon).
--
-- Une catégorie absente de cette table est présentée à l'IA par son seul nom.
-- Les descriptions servent surtout à distinguer les cas trompeurs (p. ex.
-- art_nude qui n'est PAS de la pornographie).
{
  ads: "advertising networks, ad servers and marketing/retargeting platforms."
  ai_translation: "AI-powered translation services (LLM-based), distinct from classic dictionary/translation sites."
  antivirus: "antivirus and endpoint-security vendors and their update/telemetry domains."
  apple: "Apple services and infrastructure (iCloud, App Store, push, updates)."
  art: "fine-art sites: museums, galleries, art history, painting and sculpture, with no nudity focus."
  art_nude: "honest art sites (painting, sculpture, art auctions, museums) that may display artistic nudes; this is NOT pornography."
  auth: "identity providers, SSO and authentication endpoints (OAuth, OpenID, login backends)."
  banking: "retail and online banking, payment processors and card networks."
  bible: "online Bibles, scripture readers and biblical reference sites."
  block_yahoo: "Yahoo domains explicitly blocked."
  books: "ebooks, book catalogues and reading platforms (not encyclopedias)."
  captive_portal: "connectivity-check and captive-portal probe endpoints (NCSI, Apple/Android captive checks)."
  catholic_media: "Catholic news outlets, radios, TV and media organisations."
  cdn: "content delivery networks and static-asset/edge hosting."
  certificates: "certificate authorities, OCSP/CRL and PKI validation endpoints."
  chartreuse: "domains related to the Carthusian order (Chartreuse)."
  cloud: "general cloud/IaaS/PaaS providers and object storage (AWS, Azure, GCP…)."
  code_hosting: "source-code hosting and software forges (GitHub, GitLab…)."
  culture: "general cultural sites: heritage, theatre, literature, cultural institutions."
  dating: "dating and matchmaking services."
  devices: "IoT and connected-device manufacturer backends and telemetry."
  dev_tools: "developer tooling, package registries, CI/CD and APIs for developers."
  dictionaries: "monolingual dictionaries and lexical reference sites."
  directories: "business/web directories and listing sites."
  drugs: "illegal drugs, narcotics promotion or sale."
  ebay: "eBay marketplace domains."
  education: "schools, universities, e-learning and educational resources."
  email: "webmail and email service providers/backends."
  encyclopedias: "encyclopedias and structured knowledge bases (Wikipedia-like)."
  esoteric: "esotericism, occultism, astrology, divination and the paranormal."
  farm: "agriculture, farming and agricultural supply sites."
  file_transfer: "file-sharing and large-file transfer services."
  finance: "investing, markets, trading and financial news/data."
  forums: "discussion forums and message boards."
  gambling: "online gambling, betting and casinos."
  google: "Google services and infrastructure."
  google_extensions: "Google extension/update endpoints."
  government: "government, public administration and official state sites."
  gps: "GPS/location and assisted-positioning backend services."
  hate: "hate speech, racism and discriminatory content."
  health: "health, medical information, hospitals and pharmacies."
  images: "image hosting and stock-photo galleries."
  insurance: "insurance companies and brokers."
  lilo: "Lilo search-engine domains."
  liturgy: "Catholic liturgy, breviary, Mass texts and liturgical calendars."
  malware: "malware distribution, command-and-control and known-malicious hosts."
  maps: "maps and geographic/navigation services."
  messaging: "instant-messaging and chat services."
  mozilla: "Mozilla services and infrastructure."
  music: "music streaming, catalogues and artist sites."
  news: "general-interest news outlets and press."
  non_catholic: "non-Catholic religious sites (other Christian confessions and other religions)."
  ntp: "network time protocol servers."
  nxdomain: "domains expected to resolve to NXDOMAIN / deliberately non-existent."
  office: "office suites and productivity collaboration backends."
  open: "open/explicitly allowed catch-all entries."
  personal: "personal homepages and blogs."
  phone: "telephony, VoIP and mobile-carrier services."
  piracy: "copyright-infringing distribution of media or software."
  podcasts: "podcast hosting and directories."
  porn: "pornography and sexually explicit content."
  postal: "postal services and parcel tracking."
  push_notifications: "push-notification delivery backends."
  real_estate: "real-estate listings and property sites."
  religious: "Catholic religious sites (parishes, orders, apostolates, devotions)."
  remote_access: "remote-desktop and remote-access services."
  science: "science, research and scientific publications."
  sects: "sects and cults."
  shopping: "online retail and e-commerce stores."
  skype: "Skype domains."
  social_media: "social networks and social-media platforms."
  spotify: "Spotify domains."
  stemarie: "domains related to Sainte-Marie (specific institution)."
  streaming_video: "video streaming platforms and VOD services."
  students_fsspx: "allowlist for FSSPX students."
  technical: "low-level technical/infrastructure domains not fitting another bucket."
  trackers: "user-tracking, analytics and telemetry beacons."
  translation: "classic (non-AI) translation and bilingual dictionary services."
  transport: "public transport, schedules and mobility operators."
  travel_booking: "travel, flight/hotel booking and reservation platforms."
  updates: "software-update and patch-distribution endpoints."
  utilities: "utility web services and miscellaneous helper tools."
  vatican: "Vatican (Holy See) official domains."
  video: "general video hosting (non-streaming-platform)."
  video_conferencing: "video-conferencing and online-meeting services."
  violence: "graphic violence and gore."
  weapons: "firearms and weapons sale or promotion."
  weather: "weather forecasts and meteorological data."
  wikipedia: "Wikipedia and Wikimedia domains."
}
