local json = require("json")
local clean
clean = function(self, domain)
  if not (domain) then
    return nil
  end
  domain = {
    domain = gsub("^%s*(.*)%s*$", "%1")
  }
  if domain == "" then
    return nil
  end
  domain = {
    domain = gsub("^%*. ", "")
  }
  return {
    domain = lower()
  }
end
local f = io.open("cfg/idefix3.json", "r")
local content = {
  f = read("*all")
}
local _ = {
  f = close()
}
local data = json.decode(content)
local lists_dir = "cfg/esm/listes"
os.execute("mkdir -p " .. tostring(lists_dir))
local groups = data.groups or { }
for group_name, group_data in pairs(groups) do
  local domains = group_data.dest_domains or { }
  local cleaned = { }
  for _index_0 = 1, #domains do
    local d = domains[_index_0]
    local c = clean(d)
    if c then
      table.insert(cleaned, c)
    end
  end
  table.sort(cleaned)
  if #cleaned > 0 then
    local lf = io.open(tostring(lists_dir) .. "/" .. tostring(group_name) .. ".txt", "w")
  end
  for i = 1, #cleaned do
    _ = {
      lf = write(tostring(cleaned[i]) .. "\n")
    }
    _ = {
      lf = close()
    }
  end
end
local save_list
save_list = function(self, name, domains)
  local cleaned = { }
  for _index_0 = 1, #domains do
    local d = domains[_index_0]
    local c = clean(d)
    if c then
      table.insert(cleaned, c)
    end
  end
  table.sort(cleaned)
  local lf = io.open(tostring(lists_dir) .. "/" .. tostring(name) .. ".txt", "w")
  for i = 1, #cleaned do
    _ = {
      lf = write(tostring(cleaned[i]) .. "\n")
    }
  end
  return {
    lf = close()
  }
end
local yahoo_rule = data.rules["block yahoo search"]
if yahoo_rule then
  save_list("block_yahoo", yahoo_rule.dest_domains)
end
local spotify_rule = data.rules["Salon profs"]
if spotify_rule then
  save_list("spotify", spotify_rule.dest_domains)
end
local macs_map = { }
local maclists = {
  profs = { },
  abbes = { },
  eleves_limites = { },
  salon_profs = { },
  defaut = { }
}
local profile_map = {
  ["Internet autorisé (filtré par catégories \"large\")"] = "profs",
  ["Internet filtré par défaut (prieuré)"] = "defaut",
  ["Internet limité (liste blanche)"] = "eleves_limites"
}
for profile_name, profile_data in pairs(data.users) do
  local group_key = profile_map[profile_name]
  for user_key, user_data in pairs(profile_data) do
    if type(user_data) == "table" and user_data.devices then
      for dev_name, dev_data in pairs(user_data.devices) do
        local mac = dev_data.mac
        if mac then
          macs_map[dev_name] = mac
          local target = group_key
          if user_key == "Salon profs" then
            target = "salon_profs"
          elseif user_key == "Abbés" then
            target = "abbes"
          end
          if target then
            local found = false
            local _list_0 = maclists[target]
            for _index_0 = 1, #_list_0 do
              local m = _list_0[_index_0]
              if m == dev_name then
                found = true
              end
            end
            if not (found) then
              table.insert(maclists[target], dev_name)
            end
          end
        end
      end
    end
  end
end
local yml = "# Generated by idefix2filter.moon\n"
yml = yml .. "domainlists_dir: /etc/custos/lists\ncustom_lists_dir: /etc/custos/lists/custom\n\n"
yml = yml .. "macs:\n"
for name, mac in pairs(macs_map) do
  yml = yml .. "  " .. tostring(name) .. ": " .. tostring(mac) .. "\n"
end
yml = yml .. "\nmaclists:\n"
for group, members in pairs(maclists) do
  yml = yml .. "  " .. tostring(group) .. ": ["
  for i, m in ipairs(members) do
    yml = yml .. tostring(m) .. tostring(i == #members and "" or ", ")
  end
  yml = yml .. "]\n"
end
yml = yml .. "\nrules:\n"
local rules = { }
table.insert(rules, {
  desc = "Blocages prioritaires",
  act = "deny",
  cond = "to_domainlist: custom/block_yahoo"
})
table.insert(rules, {
  desc = "Accès total Profs",
  act = "allow",
  cond = "from_maclist: profs"
})
table.insert(rules, {
  desc = "Infrastructure et local",
  act = "allow",
  cond = "to_domains: [local, lan, home.arpa]"
})
table.insert(rules, {
  desc = "Profil Abbés",
  act = "allow",
  cond = "from_maclist: abbes, to_domainlists: [custom/addenda_religieux, custom/addenda_auth, custom/addenda_banque, custom/addenda_cloud, custom/addenda_communication, custom/addenda_courriel, custom/addenda_gps, custom/addenda_maj, custom/addenda_peripheriques, custom/default_fsspx, custom/limite_eleves_fsspx]"
})
table.insert(rules, {
  desc = "Profil Élèves Limités",
  act = "allow",
  cond = "from_maclist: eleves_limites, to_domainlists: [custom/addenda_apple, custom/addenda_cloud, custom/addenda_courriel, custom/addenda_maj, custom/addenda_peripheriques, custom/addenda_stemarie, custom/default_fsspx, custom/limite_eleves_fsspx]"
})
table.insert(rules, {
  desc = "Spotify Salon Profs",
  act = "allow",
  cond = "from_maclist: salon_profs, to_domainlist: custom/spotify"
})
table.insert(rules, {
  desc = "Verdict Final",
  act = "deny"
})
for _, r in ipairs(rules) do
  yml = yml .. "- description: " .. tostring(r.desc) .. "\n  actions: [" .. tostring(r.act) .. "]\n"
  if r.cond then
    yml = yml .. "  conditions:\n    " .. tostring(r.cond) .. "\n"
  end
  yml = yml .. "\n"
end
-- Note: filter.yml has been removed from the project
return {
  f_out = close()
}
