local util = require("ipparse.lib.util")
local test
test = util.test
local eth = require("ipparse.l2.ethernet")
local sp = require("ipparse.lib.pack_compat").pack
local eth_raw = sp("c6c6>H", "\xaa\xbb\xcc\xdd\xee\xff", "\x00\x11\x22\x33\x44\x55", 0x0800)
test("mac2s converts binary to string", function()
  local result = eth.mac2s("\xaa\xbb\xcc\xdd\xee\xff")
  return assert(result == "aa:bb:cc:dd:ee:ff", "expected 'aa:bb:cc:dd:ee:ff', got '" .. tostring(result) .. "'")
end)
test("s2mac converts string to binary", function()
  local result = eth.s2mac("aa:bb:cc:dd:ee:ff")
  return assert(result == "\xaa\xbb\xcc\xdd\xee\xff", "s2mac failed")
end)
test("mac2s/s2mac round-trip", function()
  local original = "\x12\x34\x56\x78\x9a\xbc"
  return assert(eth.s2mac(eth.mac2s(original)) == original, "mac2s/s2mac round-trip failed")
end)
test("parse extracts dst MAC", function()
  local frame, next_off = eth.parse(eth_raw, 1)
  return assert(frame.dst == "\xaa\xbb\xcc\xdd\xee\xff", "dst MAC mismatch")
end)
test("parse extracts src MAC", function()
  local frame, next_off = eth.parse(eth_raw, 1)
  return assert(frame.src == "\x00\x11\x22\x33\x44\x55", "src MAC mismatch")
end)
test("parse extracts protocol", function()
  local frame, next_off = eth.parse(eth_raw, 1)
  return assert(frame.protocol == 0x0800, "protocol should be 0x0800, got " .. tostring(frame.protocol))
end)
test("parse returns correct next offset", function()
  local frame, next_off = eth.parse(eth_raw, 1)
  return assert(next_off == 15, "next_off should be 15 (after 14-byte header), got " .. tostring(next_off))
end)
test("parse data_off is 15", function()
  local frame, next_off = eth.parse(eth_raw, 1)
  return assert(frame.data_off == 15, "data_off should be 15, got " .. tostring(frame.data_off))
end)
test("proto IP4 == 0x0800", function()
  return assert(eth.proto.IP4 == 0x0800, "IP4 proto should be 0x0800, got " .. tostring(eth.proto.IP4))
end)
test("proto reverse lookup 0x0800 == IP4", function()
  return assert(eth.proto[0x0800] == "IP4", "reverse lookup 0x0800 should be 'IP4', got '" .. tostring(eth.proto[0x0800]) .. "'")
end)
test("proto IP6 == 0x86DD", function()
  return assert(eth.proto.IP6 == 0x86DD, "IP6 proto should be 0x86DD")
end)
test("new + tostring round-trip", function()
  local frame = eth.new({
    dst = "\xaa\xbb\xcc\xdd\xee\xff",
    src = "\x00\x11\x22\x33\x44\x55",
    protocol = 0x0800
  })
  local raw = tostring(frame)
  local parsed, _ = eth.parse(raw, 1)
  assert(parsed.dst == "\xaa\xbb\xcc\xdd\xee\xff", "round-trip dst mismatch")
  assert(parsed.src == "\x00\x11\x22\x33\x44\x55", "round-trip src mismatch")
  return assert(parsed.protocol == 0x0800, "round-trip protocol mismatch")
end)
return util.summary("l2/ethernet")
