local QUEUE_QUESTIONS = "0-1"
local QUEUE_RESPONSES = "4"
local QUEUE_CAPTIVE = "20"
local QUEUE_REJECT = "10-11"
local QUEUE_AUTH = "5"
local LOG_LEVEL = "INFO"
local NFT_FAMILY = "bridge"
local NFT_FAMILY6 = "bridge"
local NFT_TABLE = "dns-filter-bridge"
local NFT_SET_IP4 = "ip4_allowed"
local NFT_SET_IP6 = "ip6_allowed"
local NFT_SET_MAC4 = "mac4_allowed"
local NFT_SET_MAC6 = "mac6_allowed"
local NFT_IP_TIMEOUT = "2m"
local NFT_ADD_RETRY_COUNT = 3
local NFT_ADD_BACKOFF_MS = {
  20,
  50,
  100
}
local NFT_ADD_FAILURE_POLICY = "fail-closed"
local IPC_PENDING_TTL = 5
local IPC_MATCH_RETRY_ENABLED = true
local IPC_MATCH_RETRY_COUNT = 5
local IPC_MATCH_RETRY_SLEEP_MS = 20
local CLIENT_EXPIRY = 300
local FORCED_TTL = 60
local DNS_PORT = 53
local AF_INET = 2
local AF_INET6 = 10
local MAC_LEARNER_QUERY_SOCK = "/var/run/custos/mac_query.sock"
local MAC_LEARNER_LEARN_MSG_SIZE = 22
local MAC_LEARNER_ENTRY_TTL = 300
local AUTH_SESSIONS_FILE = "./tmp/sessions.lua"
local EVENTS_DIR = "/tmp/custos/events"
local EVENTS_MAX_AGE_HOURS = 168
local EVENTS_MIN_FREE_PCT = 30
local DEST_WHITELIST = { }
local ALLOWED_DOMAINS = {
  "local",
  "lan",
  "home.arpa"
}
local NFT_EXTRA_RULES = { }
return {
  QUEUE_QUESTIONS = QUEUE_QUESTIONS,
  QUEUE_RESPONSES = QUEUE_RESPONSES,
  QUEUE_CAPTIVE = QUEUE_CAPTIVE,
  QUEUE_REJECT = QUEUE_REJECT,
  QUEUE_AUTH = QUEUE_AUTH,
  NFT_FAMILY = NFT_FAMILY,
  NFT_FAMILY6 = NFT_FAMILY6,
  NFT_TABLE = NFT_TABLE,
  NFT_SET_IP4 = NFT_SET_IP4,
  NFT_SET_IP6 = NFT_SET_IP6,
  NFT_SET_MAC4 = NFT_SET_MAC4,
  NFT_SET_MAC6 = NFT_SET_MAC6,
  NFT_IP_TIMEOUT = NFT_IP_TIMEOUT,
  NFT_ADD_RETRY_COUNT = NFT_ADD_RETRY_COUNT,
  NFT_ADD_BACKOFF_MS = NFT_ADD_BACKOFF_MS,
  NFT_ADD_FAILURE_POLICY = NFT_ADD_FAILURE_POLICY,
  IPC_PENDING_TTL = IPC_PENDING_TTL,
  IPC_MATCH_RETRY_ENABLED = IPC_MATCH_RETRY_ENABLED,
  IPC_MATCH_RETRY_COUNT = IPC_MATCH_RETRY_COUNT,
  IPC_MATCH_RETRY_SLEEP_MS = IPC_MATCH_RETRY_SLEEP_MS,
  CLIENT_EXPIRY = CLIENT_EXPIRY,
  MAC_LEARNER_QUERY_SOCK = MAC_LEARNER_QUERY_SOCK,
  MAC_LEARNER_LEARN_MSG_SIZE = MAC_LEARNER_LEARN_MSG_SIZE,
  MAC_LEARNER_ENTRY_TTL = MAC_LEARNER_ENTRY_TTL,
  FORCED_TTL = FORCED_TTL,
  DNS_PORT = DNS_PORT,
  AF_INET = AF_INET,
  AF_INET6 = AF_INET6,
  AUTH_SESSIONS_FILE = AUTH_SESSIONS_FILE,
  EVENTS_DIR = EVENTS_DIR,
  EVENTS_MAX_AGE_HOURS = EVENTS_MAX_AGE_HOURS,
  EVENTS_MIN_FREE_PCT = EVENTS_MIN_FREE_PCT,
  DEST_WHITELIST = DEST_WHITELIST,
  ALLOWED_DOMAINS = ALLOWED_DOMAINS,
  NFT_EXTRA_RULES = NFT_EXTRA_RULES,
  LOG_LEVEL = LOG_LEVEL
}
