return describe("FFI Definitions Syntax", function()
  it("ffi_defs requires without errors", function()
    local ffi_defs = require("ffi_defs")
    return assert.is_not_nil(ffi_defs)
  end)
  it("FFI definitions are accessible", function()
    local ffi_defs = require("ffi_defs")
    local C = ffi_defs.C
    assert.is_not_nil(C)
    assert.is_not_nil(C.socket)
    assert.is_not_nil(C.bind)
    assert.is_not_nil(C.listen)
    assert.is_not_nil(C.accept)
    return assert.is_not_nil(C.connect)
  end)
  it("socket structures are defined", function()
    local ffi_defs = require("ffi_defs")
    local ffi = require("ffi")
    local addr = ffi.new("struct sockaddr")
    local addr4 = ffi.new("struct sockaddr_in")
    local addr6 = ffi.new("struct sockaddr_in6")
    local addr_un = ffi.new("struct sockaddr_un")
    local addr_ll = ffi.new("struct sockaddr_ll")
    assert.is_not_nil(addr)
    assert.is_not_nil(addr4)
    assert.is_not_nil(addr6)
    assert.is_not_nil(addr_un)
    return assert.is_not_nil(addr_ll)
  end)
  it("pollfd structure is defined", function()
    local ffi_defs = require("ffi_defs")
    local ffi = require("ffi")
    local pfd = ffi.new("struct pollfd")
    return assert.is_not_nil(pfd)
  end)
  return it("timeval and fd_set structures are defined", function()
    local ffi_defs = require("ffi_defs")
    local ffi = require("ffi")
    local tv = ffi.new("struct timeval")
    local fds = ffi.new("struct fd_set")
    assert.is_not_nil(tv)
    return assert.is_not_nil(fds)
  end)
end)
