describe("cert_cache (LRU with TTL)", function()
  it("should insert and retrieve an entry", function()
    local cache_module = require("auth.cert_cache")
    local cache = cache_module.create_cache(10, 3600)
    local cert = "-----BEGIN CERTIFICATE-----\ntest\n-----END CERTIFICATE-----"
    local key = "-----BEGIN PRIVATE KEY-----\ntest\n-----END PRIVATE KEY-----"
    local ok = cache.set("example.com", cert, key, nil)
    assert(ok == true, "set should return true")
    local entry = cache.get("example.com")
    assert(entry ~= nil, "entry should exist")
    assert(entry.cert_pem == cert, "cert_pem should match")
    return assert(entry.key_pem == key, "key_pem should match")
  end)
  it("should handle case-insensitive hostnames", function()
    local cache_module = require("auth.cert_cache")
    local cache = cache_module.create_cache(10, 3600)
    local cert = "test_cert"
    cache.set("Example.COM", cert, "test_key", nil)
    local entry = cache.get("example.com")
    assert(entry ~= nil, "should find with lowercase")
    return assert(entry.cert_pem == cert, "cert should match")
  end)
  it("should evict oldest entry when full", function()
    local cache_module = require("auth.cert_cache")
    local cache = cache_module.create_cache(3, 3600)
    for i = 1, 4 do
      cache.set("host" .. tostring(i) .. ".com", "cert" .. tostring(i), "key" .. tostring(i), nil)
    end
    local stats = cache.stats()
    assert(stats.size <= 3, "cache should not exceed max size")
    local entry1 = cache.get("host1.com")
    assert(entry1 == nil, "oldest entry should be evicted")
    local entry4 = cache.get("host4.com")
    return assert(entry4 ~= nil, "newest entry should exist")
  end)
  return it("should handle expired entries", function()
    local cache_module = require("auth.cert_cache")
    local cache = cache_module.create_cache(10, 1)
    cache.set("example.com", "cert", "key", nil)
    return os.sleep(2)
  end)
end)
describe("sni_extractor", function()
  it("should parse a minimal valid TLS ClientHello", function()
    local sni_module = require("auth.sni_extractor")
    local bad_data = "xyz"
    local hostname = sni_module.extract_sni(bad_data)
    return assert(hostname == nil, "should return nil for invalid data")
  end)
  return it("should return nil for non-handshake records", function()
    local sni_module = require("auth.sni_extractor")
    local data = string.char(0x17) .. string.rep("\x00", 100)
    local hostname = sni_module.extract_sni(data)
    return assert(hostname == nil, "should return nil for non-handshake")
  end)
end)
return describe("cert_generator", function()
  return it("should validate input parameters", function()
    local gen = require("auth.cert_generator")
    local cert, ok, err = gen.generate_self_signed("", "test.com", { })
    assert(ok == false, "should fail with empty key")
    cert, ok, err = gen.generate_self_signed("test_key", "", { })
    return assert(ok == false, "should fail with empty CN")
  end)
end)
