return describe("nft_queue per-rule sets (Phase C1)", function()
  local nft_queue, get_set_name, cmd_for, sanitize_rule_id
  before_each(function()
    nft_queue = require("nft_queue")
    get_set_name = nft_queue.get_set_name
    cmd_for = nft_queue.cmd_for
    sanitize_rule_id = nft_queue.sanitize_rule_id
  end)
  describe("sanitize_rule_id", function()
    it("returns empty string for nil", function()
      return assert.equal("", sanitize_rule_id(nil))
    end)
    it("returns empty string for empty string", function()
      return assert.equal("", sanitize_rule_id(""))
    end)
    it("returns rule_id as-is for valid hex", function()
      return assert.equal("61626364", sanitize_rule_id("61626364"))
    end)
    it("truncates to 126 chars for oversized rule_id", function()
      local long_id = string.rep("a", 150)
      local result = sanitize_rule_id(long_id)
      return assert.equal(126, #result)
    end)
    return it("converts non-string to string", function()
      local result = sanitize_rule_id(12345)
      return assert.equal("12345", result)
    end)
  end)
  describe("get_set_name", function()
    it("returns nil for empty rule_id and ip4 (per-rule required)", function()
      local result = get_set_name("ip4", "")
      return assert.is_nil(result)
    end)
    it("returns nil for empty rule_id and ip6 (per-rule required)", function()
      local result = get_set_name("ip6", "")
      return assert.is_nil(result)
    end)
    it("returns nil for empty rule_id and mac4 (per-rule required)", function()
      local result = get_set_name("mac4", "")
      return assert.is_nil(result)
    end)
    it("returns nil for empty rule_id and mac6 (per-rule required)", function()
      local result = get_set_name("mac6", "")
      return assert.is_nil(result)
    end)
    it("returns per-rule set rule_test_ip4 for rule_id and ip4", function()
      local result = get_set_name("ip4", "test")
      return assert.equal("rule_test_ip4", result)
    end)
    it("returns per-rule set rule_test_ip6 for rule_id and ip6", function()
      local result = get_set_name("ip6", "test")
      return assert.equal("rule_test_ip6", result)
    end)
    it("returns per-rule set rule_test_mac4 for rule_id and mac4", function()
      local result = get_set_name("mac4", "test")
      return assert.equal("rule_test_mac4", result)
    end)
    it("returns per-rule set rule_test_mac6 for rule_id and mac6", function()
      local result = get_set_name("mac6", "test")
      return assert.equal("rule_test_mac6", result)
    end)
    it("returns nil for nil kind with rule_id", function()
      local result = get_set_name("invalid", "test")
      return assert.is_nil(result)
    end)
    return it("handles hex-encoded rule_id", function()
      local result = get_set_name("ip4", "61626364")
      return assert.equal("rule_61626364_ip4", result)
    end)
  end)
  describe("cmd_for with rule_id", function()
    it("generates IPv4 add element command with rule_id", function()
      local cmd = cmd_for("ip4", "192.168.1.100", "10.0.0.1", "test", "60s")
      assert.match("add element bridge dns%-filter%-bridge rule_test_ip4", cmd)
      assert.match("192%.168%.1%.100", cmd)
      assert.match("10%.0%.0%.1", cmd)
      return assert.match("timeout 60s", cmd)
    end)
    it("generates IPv6 add element command with rule_id", function()
      local cmd = cmd_for("ip6", "2001:db8::1", "2001:db8::2", "test", "120s")
      assert.match("add element bridge dns%-filter%-bridge rule_test_ip6", cmd)
      assert.match("2001:db8::1", cmd)
      assert.match("2001:db8::2", cmd)
      return assert.match("timeout 120s", cmd)
    end)
    it("generates MAC4 add element command with rule_id", function()
      local cmd = cmd_for("mac4", "aa:bb:cc:dd:ee:ff", "10.0.0.1", "test", "180s")
      assert.match("add element bridge dns%-filter%-bridge rule_test_mac4", cmd)
      assert.match("aa:bb:cc:dd:ee:ff", cmd)
      return assert.match("timeout 180s", cmd)
    end)
    it("generates MAC6 add element command with rule_id", function()
      local cmd = cmd_for("mac6", "aa:bb:cc:dd:ee:ff", "2001:db8::1", "test", "300s")
      assert.match("add element bridge dns%-filter%-bridge rule_test_mac6", cmd)
      assert.match("aa:bb:cc:dd:ee:ff", cmd)
      return assert.match("timeout 300s", cmd)
    end)
    it("falls back to global sets for empty rule_id", function()
      local cmd = cmd_for("ip4", "192.168.1.100", "10.0.0.1", "", "60s")
      return assert.match("add element bridge dns%-filter%-bridge ip4_allowed", cmd)
    end)
    it("returns nil for invalid kind", function()
      local cmd = cmd_for("invalid", "192.168.1.100", "10.0.0.1", "test", "60s")
      return assert.is_nil(cmd)
    end)
    it("sanitizes timeout to default on invalid", function()
      local cmd = cmd_for("ip4", "192.168.1.100", "10.0.0.1", "test", "invalid_timeout")
      assert.is_not_nil(cmd)
      return assert.match("timeout 2m", cmd)
    end)
    return it("handles long rule_id", function()
      local long_id = string.rep("a", 100)
      local cmd = cmd_for("ip4", "192.168.1.100", "10.0.0.1", long_id, "60s")
      assert.is_not_nil(cmd)
      return assert.match("rule_" .. string.rep("a", 100) .. "_ip4", cmd)
    end)
  end)
  describe("per-rule set naming consistency", function()
    it("same rule_id and kind produce same set name", function()
      local name1 = get_set_name("ip4", "rule123")
      local name2 = get_set_name("ip4", "rule123")
      return assert.equal(name1, name2)
    end)
    it("different kinds produce different set names for same rule_id", function()
      local name_ip4 = get_set_name("ip4", "rule123")
      local name_ip6 = get_set_name("ip6", "rule123")
      assert.not_equal(name_ip4, name_ip6)
      assert.equal("rule_rule123_ip4", name_ip4)
      return assert.equal("rule_rule123_ip6", name_ip6)
    end)
    return it("different rule_ids produce different set names for same kind", function()
      local name1 = get_set_name("ip4", "rule1")
      local name2 = get_set_name("ip4", "rule2")
      assert.not_equal(name1, name2)
      assert.equal("rule_rule1_ip4", name1)
      return assert.equal("rule_rule2_ip4", name2)
    end)
  end)
  return describe("timeout composition (from worker_responses)", function()
    local worker_responses
    before_each(function()
      worker_responses = require("worker_responses")
    end)
    it("rr_timeout returns TTL + grace clamped to min/max", function()
      local timeout_str, timeout_num = worker_responses.rr_timeout(60)
      assert.equal("660s", timeout_str)
      return assert.equal(660, timeout_num)
    end)
    it("rr_timeout returns min for very low TTL", function()
      local timeout_str, timeout_num = worker_responses.rr_timeout(1)
      return assert.equal("601s", timeout_str)
    end)
    it("rr_timeout clamps to min boundary", function()
      local timeout_str, _ = worker_responses.rr_timeout(0)
      return assert.equal("600s", timeout_str)
    end)
    return it("rr_timeout clamps to max boundary", function()
      local timeout_str, _ = worker_responses.rr_timeout(3000000)
      return assert.equal("2592000s", timeout_str)
    end)
  end)
end)
