return describe("filter.lib.cidr_parser", function()
  local parse_cidr, parse_ipv4_cidr, parse_ipv6_cidr, validate_cidr, format_cidr
  do
    local _obj_0 = require("filter.lib.cidr_parser")
    parse_cidr, parse_ipv4_cidr, parse_ipv6_cidr, validate_cidr, format_cidr = _obj_0.parse_cidr, _obj_0.parse_ipv4_cidr, _obj_0.parse_ipv6_cidr, _obj_0.validate_cidr, _obj_0.format_cidr
  end
  describe("parse_ipv4_cidr", function()
    it("CIDR IPv4 standard", function()
      local r = parse_ipv4_cidr("192.168.0.0/24")
      assert.is_not_nil(r)
      assert.equals("inet", r.family)
      assert.equals(24, r.prefix)
      assert.equals("192.168.0.0", r.net)
      return assert.is_true(r.is_valid)
    end)
    it("host unique /32", function()
      local r = parse_ipv4_cidr("10.0.0.1/32")
      assert.is_not_nil(r)
      return assert.equals(32, r.prefix)
    end)
    it("préfixe /0", function()
      local r = parse_ipv4_cidr("0.0.0.0/0")
      assert.is_not_nil(r)
      return assert.equals(0, r.prefix)
    end)
    it("sans masque → /32 implicite", function()
      local r = parse_ipv4_cidr("10.0.0.1")
      assert.is_not_nil(r)
      return assert.equals(32, r.prefix)
    end)
    it("nil → nil", function()
      return assert.is_nil(parse_ipv4_cidr(nil))
    end)
    it("chaîne vide → nil", function()
      return assert.is_nil(parse_ipv4_cidr(""))
    end)
    it("IPv6 → nil (mauvaise famille)", function()
      return assert.is_nil(parse_ipv4_cidr("::1/128"))
    end)
    it("préfixe > 32 → nil", function()
      return assert.is_nil(parse_ipv4_cidr("10.0.0.0/33"))
    end)
    it("octet hors plage → nil", function()
      return assert.is_nil(parse_ipv4_cidr("256.0.0.0/8"))
    end)
    return it("format invalide → nil", function()
      return assert.is_nil(parse_ipv4_cidr("not_an_ip/24"))
    end)
  end)
  describe("parse_ipv6_cidr", function()
    it("CIDR IPv6 standard", function()
      local r = parse_ipv6_cidr("2001:db8::/32")
      assert.is_not_nil(r)
      assert.equals("inet6", r.family)
      assert.equals(32, r.prefix)
      return assert.is_true(r.is_valid)
    end)
    it("loopback /128", function()
      local r = parse_ipv6_cidr("::1/128")
      assert.is_not_nil(r)
      return assert.equals(128, r.prefix)
    end)
    it("sans masque → /128 implicite", function()
      local r = parse_ipv6_cidr("::1")
      assert.is_not_nil(r)
      return assert.equals(128, r.prefix)
    end)
    it("nil → nil", function()
      return assert.is_nil(parse_ipv6_cidr(nil))
    end)
    it("IPv4 → nil (mauvaise famille)", function()
      return assert.is_nil(parse_ipv6_cidr("192.168.0.0/16"))
    end)
    return it("préfixe > 128 → nil", function()
      return assert.is_nil(parse_ipv6_cidr("::1/129"))
    end)
  end)
  describe("parse_cidr", function()
    it("détecte auto IPv4", function()
      local r = parse_cidr("10.0.0.0/8")
      assert.is_not_nil(r)
      return assert.equals("inet", r.family)
    end)
    it("détecte auto IPv6", function()
      local r = parse_cidr("fc00::/7")
      assert.is_not_nil(r)
      return assert.equals("inet6", r.family)
    end)
    return it("nil → nil", function()
      return assert.is_nil(parse_cidr(nil))
    end)
  end)
  describe("validate_cidr", function()
    it("CIDR valide → true, nil", function()
      local ok, err = validate_cidr("192.168.0.0/24")
      assert.is_true(ok)
      return assert.is_nil(err)
    end)
    return it("CIDR invalide → false, message d'erreur", function()
      local ok, err = validate_cidr("invalid")
      assert.is_false(ok)
      return assert.is_not_nil(err)
    end)
  end)
  return describe("format_cidr", function()
    it("formate un objet parsé", function()
      local r = parse_cidr("10.0.0.0/8")
      local s = format_cidr(r)
      return assert.equals("10.0.0.0/8", s)
    end)
    return it("nil → nil", function()
      return assert.is_nil(format_cidr(nil))
    end)
  end)
end)
