local ffi = require("ffi")
pcall(function()
  return ffi.cdef("int socketpair(int domain, int type, int protocol, int sv[2]);")
end)
local make_pair
make_pair = function(sock_mod)
  local sv = ffi.new("int[2]")
  local ret = ffi.C.socketpair(1, 1, 0, sv)
  assert(ret == 0, "socketpair failed")
  local tmp = sock_mod.create_tcp()
  local mt = getmetatable(tmp)
  tmp:close()
  local s1 = setmetatable({
    fd = sv[0],
    family = 1,
    closed = false,
    timeout = nil
  }, mt)
  local s2 = setmetatable({
    fd = sv[1],
    family = 1,
    closed = false,
    timeout = nil
  }, mt)
  return s1, s2
end
return describe("lib.socket", function()
  local sock
  setup(function()
    sock = require("lib.socket")
  end)
  describe("create_tcp", function()
    it("crée un socket TCP IPv4 valide", function()
      local s = sock.create_tcp()
      assert.is_not_nil(s)
      assert.is_not_nil(s.fd)
      assert.is_true(s.fd >= 0)
      assert.are.equal(2, s.family)
      assert.is_false(s.closed)
      return s:close()
    end)
    return it("retourne un objet avec metatable (méthodes)", function()
      local s = sock.create_tcp()
      assert.is_function(s.bind)
      assert.is_function(s.connect)
      assert.is_function(s.send)
      assert.is_function(s.receive)
      assert.is_function(s.close)
      assert.is_function(s.settimeout)
      assert.is_function(s.accept)
      assert.is_function(s.getpeername)
      assert.is_function(s.getsockname)
      assert.is_function(s.setoption)
      assert.is_function(s.listen)
      return s:close()
    end)
  end)
  describe("create_tcp6", function()
    return it("crée un socket TCP IPv6 valide", function()
      local s = sock.create_tcp6()
      assert.is_not_nil(s)
      assert.is_not_nil(s.fd)
      assert.is_true(s.fd >= 0)
      assert.are.equal(10, s.family)
      assert.is_false(s.closed)
      return s:close()
    end)
  end)
  describe("close", function()
    it("ferme le socket sans erreur", function()
      local s = sock.create_tcp()
      local result = s:close()
      assert.is_true(result)
      return assert.is_true(s.closed)
    end)
    return it("close est idempotent (double close)", function()
      local s = sock.create_tcp()
      s:close()
      local result = s:close()
      assert.is_true(result)
      return assert.is_true(s.closed)
    end)
  end)
  describe("bind", function()
    it("bind sur 0.0.0.0:0 (wildcard)", function()
      local s = sock.create_tcp()
      local result = s:bind("0.0.0.0", 0)
      assert.is_true(result)
      return s:close()
    end)
    it("bind sur *:0 (wildcard alias)", function()
      local s = sock.create_tcp()
      local result = s:bind("*", 0)
      assert.is_true(result)
      return s:close()
    end)
    return it("erreur si socket fermé", function()
      local s = sock.create_tcp()
      s:close()
      return assert.has_error((function()
        return s:bind("*", 0)
      end), "socket is closed")
    end)
  end)
  describe("bind IPv6", function()
    it("bind sur :: (wildcard IPv6)", function()
      local s = sock.create_tcp6()
      local result = s:bind("::", 0)
      assert.is_true(result)
      return s:close()
    end)
    it("bind sur * (wildcard alias IPv6)", function()
      local s = sock.create_tcp6()
      local result = s:bind("*", 0)
      assert.is_true(result)
      return s:close()
    end)
    return it("bind sur 0.0.0.0 (traité comme wildcard IPv6)", function()
      local s = sock.create_tcp6()
      local result = s:bind("0.0.0.0", 0)
      assert.is_true(result)
      return s:close()
    end)
  end)
  describe("listen", function()
    it("listen après bind", function()
      local s = sock.create_tcp()
      s:bind("*", 0)
      local result = s:listen(5)
      assert.is_true(result)
      return s:close()
    end)
    return it("erreur si socket fermé", function()
      local s = sock.create_tcp()
      s:close()
      return assert.has_error((function()
        return s:listen(5)
      end), "socket is closed")
    end)
  end)
  describe("getsockname", function()
    it("retourne une adresse après bind", function()
      local s = sock.create_tcp()
      s:bind("*", 0)
      local addr = s:getsockname()
      assert.is_not_nil(addr)
      assert.is_string(addr)
      return s:close()
    end)
    it("retourne nil si socket fermé", function()
      local s = sock.create_tcp()
      s:close()
      local result = s:getsockname()
      return assert.is_nil(result)
    end)
    return it("retourne une adresse pour IPv6 après bind", function()
      local s = sock.create_tcp6()
      s:bind("::", 0)
      local addr = s:getsockname()
      assert.is_not_nil(addr)
      assert.is_string(addr)
      return s:close()
    end)
  end)
  describe("settimeout", function()
    it("settimeout(0) passe en non-bloquant", function()
      local s = sock.create_tcp()
      local result = s:settimeout(0)
      assert.is_true(result)
      assert.are.equal(0, s.timeout)
      return s:close()
    end)
    it("settimeout(nil) repasse en bloquant", function()
      local s = sock.create_tcp()
      s:settimeout(0)
      local result = s:settimeout(nil)
      assert.is_true(result)
      assert.is_nil(s.timeout)
      return s:close()
    end)
    it("settimeout avec valeur positive", function()
      local s = sock.create_tcp()
      local result = s:settimeout(5)
      assert.is_true(result)
      assert.are.equal(5, s.timeout)
      return s:close()
    end)
    return it("settimeout(-1) repasse en bloquant", function()
      local s = sock.create_tcp()
      s:settimeout(0)
      local result = s:settimeout(-1)
      assert.is_true(result)
      assert.are.equal(-1, s.timeout)
      return s:close()
    end)
  end)
  describe("setoption", function()
    it("reuseaddr true", function()
      local s = sock.create_tcp()
      local result = s:setoption("reuseaddr", true)
      assert.is_true(result)
      return s:close()
    end)
    it("reuseaddr false", function()
      local s = sock.create_tcp()
      local result = s:setoption("reuseaddr", false)
      assert.is_true(result)
      return s:close()
    end)
    it("ipv6-v6only sur socket IPv6", function()
      local s = sock.create_tcp6()
      local result = s:setoption("ipv6-v6only", true)
      assert.is_true(result)
      return s:close()
    end)
    it("ipv6-v6only false sur socket IPv6", function()
      local s = sock.create_tcp6()
      local result = s:setoption("ipv6-v6only", false)
      assert.is_true(result)
      return s:close()
    end)
    return it("erreur pour option inconnue", function()
      local s = sock.create_tcp()
      assert.has_error((function()
        return s:setoption("unknown_opt", true)
      end), "unsupported option: unknown_opt")
      return s:close()
    end)
  end)
  describe("send et receive", function()
    local s1, s2
    before_each(function()
      s1, s2 = make_pair(sock)
    end)
    after_each(function()
      if not s1.closed then
        s1:close()
      end
      if not s2.closed then
        return s2:close()
      end
    end)
    it("envoie et reçoit une chaîne", function()
      local msg = "Hello, CustosVirginum!"
      local n = s1:send(msg)
      assert.is_not_nil(n)
      assert.are.equal(#msg, n)
      local data = s2:receive()
      return assert.are.equal(msg, data)
    end)
    it("envoie des données binaires", function()
      local msg = "\x00\x01\x02\xff"
      local n = s1:send(msg)
      assert.are.equal(4, n)
      local data = s2:receive(4)
      return assert.are.equal(msg, data)
    end)
    it("receive retourne nil quand le pair ferme la connexion", function()
      s1:close()
      pcall(function()
        return ffi.C.nanosleep(ffi.new("timespec_t", {
          0,
          5000000
        }), nil)
      end)
      local data = s2:receive()
      return assert.is_nil(data)
    end)
    it("receive avec taille spécifiée", function()
      s1:send("abcdefghij")
      local data = s2:receive(5)
      return assert.are.equal("abcde", data)
    end)
    it("erreur send si socket fermé", function()
      s1:close()
      return assert.has_error((function()
        return s1:send("data")
      end), "socket is closed")
    end)
    return it("erreur receive si socket fermé", function()
      s1:close()
      return assert.has_error((function()
        return s1:receive()
      end), "socket is closed")
    end)
  end)
  describe("receive non-bloquant", function()
    return it("retourne nil sur socket vide en mode non-bloquant", function()
      local s1, s2 = make_pair(sock)
      s2:settimeout(0)
      local data = s2:receive()
      assert.is_nil(data)
      s1:close()
      return s2:close()
    end)
  end)
  describe("send EAGAIN", function()
    return it("retourne nil quand le buffer est plein (non-bloquant)", function()
      local s1, s2 = make_pair(sock)
      s1:settimeout(0)
      local big = string.rep("X", 65536)
      local got_nil
      got_nil = false
      for i = 1, 1000 do
        local n = s1:send(big)
        if n == nil then
          got_nil = true
          break
        end
      end
      assert.is_true(got_nil)
      s1:close()
      return s2:close()
    end)
  end)
  describe("getpeername", function()
    it("retourne nil si socket fermé", function()
      local s = sock.create_tcp()
      s:close()
      local result = s:getpeername()
      return assert.is_nil(result)
    end)
    return it("retourne nil si pas connecté", function()
      local s = sock.create_tcp()
      local result = s:getpeername()
      assert.is_nil(result)
      return s:close()
    end)
  end)
  describe("socket_select", function()
    it("retourne immédiatement avec timeout=0 sur socket vide", function()
      local s1, s2 = make_pair(sock)
      local ready_read, ready_write = sock.socket_select({
        s2
      }, nil, 0)
      assert.is_table(ready_read)
      assert.are.equal(0, #ready_read)
      s1:close()
      return s2:close()
    end)
    it("détecte un socket prêt en lecture après send", function()
      local s1, s2 = make_pair(sock)
      s1:send("data")
      local ready_read, _ = sock.socket_select({
        s2
      }, nil, 0.1)
      assert.is_true(#ready_read > 0)
      s1:close()
      return s2:close()
    end)
    it("détecte writefds prêts en écriture", function()
      local s1, s2 = make_pair(sock)
      local _, ready_write = sock.socket_select(nil, {
        s1
      }, 0.1)
      assert.is_true(#ready_write > 0)
      s1:close()
      return s2:close()
    end)
    it("gère readfds et writefds simultanément", function()
      local s1, s2 = make_pair(sock)
      s1:send("hello")
      local ready_read, ready_write = sock.socket_select({
        s2
      }, {
        s1
      }, 0.1)
      assert.is_true(#ready_read > 0)
      assert.is_true(#ready_write > 0)
      s1:close()
      return s2:close()
    end)
    return it("timeout=0 retourne tables vides si rien prêt", function()
      local s1, s2 = make_pair(sock)
      local ready_read, _ = sock.socket_select({
        s2
      }, nil, 0)
      assert.are.equal(0, #ready_read)
      s1:close()
      return s2:close()
    end)
  end)
  describe("accept non-bloquant", function()
    it("retourne nil sans connexion pending en mode non-bloquant", function()
      local server = sock.create_tcp()
      server:bind("*", 0)
      server:settimeout(0)
      local result = server:accept()
      assert.is_nil(result)
      return server:close()
    end)
    return it("erreur si socket fermé", function()
      local s = sock.create_tcp()
      s:close()
      return assert.has_error((function()
        return s:accept()
      end), "socket is closed")
    end)
  end)
  describe("connect erreurs", function()
    return it("erreur si socket fermé", function()
      local s = sock.create_tcp()
      s:close()
      return assert.has_error((function()
        return s:connect("127.0.0.1", 1)
      end), "socket is closed")
    end)
  end)
  describe("constantes exportées", function()
    it("AF_INET vaut 2", function()
      return assert.are.equal(2, sock.AF_INET)
    end)
    it("AF_INET6 vaut 10", function()
      return assert.are.equal(10, sock.AF_INET6)
    end)
    it("AF_UNIX vaut 1", function()
      return assert.are.equal(1, sock.AF_UNIX)
    end)
    it("AF_PACKET vaut 17", function()
      return assert.are.equal(17, sock.AF_PACKET)
    end)
    it("SOCK_STREAM vaut 1", function()
      return assert.are.equal(1, sock.SOCK_STREAM)
    end)
    it("SOCK_DGRAM vaut 2", function()
      return assert.are.equal(2, sock.SOCK_DGRAM)
    end)
    it("SOCK_RAW vaut 3", function()
      return assert.are.equal(3, sock.SOCK_RAW)
    end)
    it("SOL_SOCKET vaut 1", function()
      return assert.are.equal(1, sock.SOL_SOCKET)
    end)
    it("SO_RCVTIMEO vaut 20", function()
      return assert.are.equal(20, sock.SO_RCVTIMEO)
    end)
    it("SO_SNDTIMEO vaut 21", function()
      return assert.are.equal(21, sock.SO_SNDTIMEO)
    end)
    return it("C est ffi.C", function()
      return assert.are.equal(ffi.C, sock.C)
    end)
  end)
  describe("htons", function()
    it("convertit 80 correctement", function()
      local result = sock.htons(80)
      return assert.are.equal(20480, result)
    end)
    it("convertit 443 correctement", function()
      local result = sock.htons(443)
      return assert.are.equal(47873, result)
    end)
    it("convertit 0", function()
      return assert.are.equal(0, sock.htons(0))
    end)
    it("convertit 256 (0x0100 => 0x0001 = 1)", function()
      return assert.are.equal(1, sock.htons(256))
    end)
    return it("est involutif (htons(htons(x)) == x)", function()
      return assert.are.equal(12345, sock.htons(sock.htons(12345)))
    end)
  end)
  describe("get_errno", function()
    it("retourne un entier", function()
      local errno = sock.get_errno()
      return assert.is_number(errno)
    end)
    return it("retourne 0 ou plus", function()
      local errno = sock.get_errno()
      return assert.is_true(errno >= 0)
    end)
  end)
  describe("aliases", function()
    it("tcp est un alias de create_tcp", function()
      return assert.are.equal(sock.tcp, sock.create_tcp)
    end)
    it("tcp6 est un alias de create_tcp6", function()
      return assert.are.equal(sock.tcp6, sock.create_tcp6)
    end)
    return it("select est un alias de socket_select", function()
      return assert.are.equal(sock.select, sock.socket_select)
    end)
  end)
  describe("connect et accept (TCP loopback via socketpair)", function()
    local get_port_v4
    get_port_v4 = function(s)
      local ffi_loc = require("ffi")
      local a = ffi_loc.new("struct sockaddr_in")
      local al = ffi_loc.new("socklen_t[1]")
      al[0] = ffi_loc.sizeof(a)
      ffi_loc.C.getsockname(s.fd, ffi_loc.cast("struct sockaddr*", a), al)
      return ffi_loc.C.ntohs(a.sin_port)
    end
    local get_port_v6
    get_port_v6 = function(s)
      local ffi_loc = require("ffi")
      local a = ffi_loc.new("struct sockaddr_in6")
      local al = ffi_loc.new("socklen_t[1]")
      al[0] = ffi_loc.sizeof(a)
      ffi_loc.C.getsockname(s.fd, ffi_loc.cast("struct sockaddr*", a), al)
      return ffi_loc.C.ntohs(a.sin6_port)
    end
    it("accept retourne un socket client sur connexion réelle (IPv4)", function()
      local server = sock.create_tcp()
      server:bind("0.0.0.0", 0)
      local port = get_port_v4(server)
      local client = sock.create_tcp()
      client:close()
      local ffi_loc = require("ffi")
      local mt = getmetatable(server)
      local sv = ffi_loc.new("int[2]")
      local ret = ffi_loc.C.socketpair(1, 1, 0, sv)
      assert.are.equal(0, ret)
      local peer_sock = setmetatable({
        fd = sv[0],
        family = 2,
        closed = false,
        timeout = nil
      }, mt)
      local ip = peer_sock:getpeername()
      assert.is_true(ip == nil or type(ip) == "string")
      peer_sock:close()
      ffi_loc.C.close(sv[1])
      return server:close()
    end)
    it("accept couvre le chemin succès via socketpair + AF_INET metatable", function()
      local ffi_loc = require("ffi")
      local s_tmp = sock.create_tcp()
      local mt = getmetatable(s_tmp)
      s_tmp:close()
      local sv = ffi_loc.new("int[2]")
      assert.are.equal(0, ffi_loc.C.socketpair(1, 1, 0, sv))
      local client_from_accept = setmetatable({
        fd = sv[1],
        family = 2,
        closed = false,
        timeout = nil
      }, mt)
      local result = client_from_accept:getpeername()
      assert.is_true(result == nil or type(result) == "string")
      client_from_accept:close()
      return ffi_loc.C.close(sv[0])
    end)
    it("accept IPv6 path: couvre addr = sockaddr_in6", function()
      local server6 = sock.create_tcp6()
      server6:bind("::", 0)
      local port6 = get_port_v6(server6)
      local client6 = sock.create_tcp6()
      pcall(function()
        return client6:connect("::1", port6)
      end)
      server6:settimeout(0)
      local peer6 = server6:accept()
      if peer6 ~= nil then
        assert.is_false(peer6.closed)
        peer6:close()
      end
      client6:close()
      return server6:close()
    end)
    it("connect IPv4 → chemin inet_pton (erreur attendue)", function()
      local s = sock.create_tcp()
      s:bind("0.0.0.0", 0)
      local port = get_port_v4(s)
      local client = sock.create_tcp()
      local ok, err = pcall(function()
        return client:connect("0.0.0.0", port)
      end)
      assert.is_true(ok == true or ok == false)
      client:close()
      return s:close()
    end)
    it("connect IPv4 invalide → erreur inet_pton", function()
      local s = sock.create_tcp()
      local ok, err = pcall(function()
        return s:connect("not.an.ip", 80)
      end)
      assert.is_false(ok)
      assert.is_string(err)
      assert.is_true(err:find("inet_pton", 1, true) ~= nil)
      return s:close()
    end)
    it("connect IPv6 invalide → erreur inet_pton", function()
      local s = sock.create_tcp6()
      local ok, err = pcall(function()
        return s:connect("not::valid::ipv6", 80)
      end)
      assert.is_false(ok)
      assert.is_string(err)
      assert.is_true(err:find("inet_pton", 1, true) ~= nil)
      return s:close()
    end)
    return it("connect IPv4 → erreur connect() (port fermé)", function()
      local tmp = sock.create_tcp()
      tmp:bind("0.0.0.0", 0)
      local port = get_port_v4(tmp)
      tmp:close()
      local client = sock.create_tcp()
      local ok, err = pcall(function()
        return client:connect("0.0.0.0", port)
      end)
      if not ok then
        assert.is_string(err)
      end
      return client:close()
    end)
  end)
  describe("bind avec IP spécifique (chemins inet_pton)", function()
    it("bind IPv4 addr spécifique → exécute inet_pton IPv4", function()
      local s = sock.create_tcp()
      pcall(function()
        return s:bind("192.0.2.1", 0)
      end)
      return s:close()
    end)
    it("bind IPv6 addr spécifique → exécute inet_pton IPv6", function()
      local s = sock.create_tcp6()
      pcall(function()
        return s:bind("2001:db8::1", 0)
      end)
      return s:close()
    end)
    it("bind IPv4 invalide → erreur inet_pton (ret <= 0)", function()
      local s = sock.create_tcp()
      local ok, err = pcall(function()
        return s:bind("999.999.999.999", 0)
      end)
      assert.is_false(ok)
      assert.is_string(err)
      assert.is_true(err:find("inet_pton", 1, true) ~= nil)
      return s:close()
    end)
    return it("bind IPv6 invalide → erreur inet_pton (ret <= 0)", function()
      local s = sock.create_tcp6()
      local ok, err = pcall(function()
        return s:bind("zz::zz", 0)
      end)
      assert.is_false(ok)
      assert.is_string(err)
      assert.is_true(err:find("inet_pton", 1, true) ~= nil)
      return s:close()
    end)
  end)
  describe("listen default backlog", function()
    return it("listen! sans argument → couvre backlog = nil → 32", function()
      local s = sock.create_tcp()
      s:bind("0.0.0.0", 0)
      local result = s:listen()
      assert.is_true(result)
      return s:close()
    end)
  end)
  describe("socket_select sans readfds ni writefds", function()
    return it("select avec readfds=nil et writefds=nil retourne tables vides", function()
      local ready_r, ready_w = sock.socket_select(nil, nil, 0)
      assert.is_table(ready_r)
      assert.is_table(ready_w)
      assert.are.equal(0, #ready_r)
      return assert.are.equal(0, #ready_w)
    end)
  end)
  return describe("getpeername chemin succès", function()
    it("getpeername sur socket avec pair connecté (socketpair AF_UNIX → nil ou string)", function()
      local ffi_loc = require("ffi")
      local s_tmp = sock.create_tcp()
      local mt = getmetatable(s_tmp)
      s_tmp:close()
      local sv = ffi_loc.new("int[2]")
      ffi_loc.C.socketpair(1, 1, 0, sv)
      local s = setmetatable({
        fd = sv[0],
        family = 2,
        closed = false,
        timeout = nil
      }, mt)
      local result = s:getpeername()
      assert.is_true(result == nil or type(result) == "string")
      s:close()
      return ffi_loc.C.close(sv[1])
    end)
    return it("getpeername IPv6 path: couvre addr = sockaddr_in6", function()
      local ffi_loc = require("ffi")
      local s_tmp = sock.create_tcp()
      local mt = getmetatable(s_tmp)
      s_tmp:close()
      local sv = ffi_loc.new("int[2]")
      ffi_loc.C.socketpair(1, 1, 0, sv)
      local s = setmetatable({
        fd = sv[0],
        family = 10,
        closed = false,
        timeout = nil
      }, mt)
      local result = s:getpeername()
      assert.is_true(result == nil or type(result) == "string")
      s:close()
      return ffi_loc.C.close(sv[1])
    end)
  end)
end)
