local util = require("ipparse.lib.util")
local test
test = util.test
local prot = require("ipparse.l4.quic.v1.protection")
local hex_to_bin
hex_to_bin = require("ipparse.lib.hkdf").hex_to_bin
local bin2hex
bin2hex = function(s)
  return s:gsub(".", function(c)
    return string.format("%02x", string.byte(c))
  end)
end
test("protection: construct_nonce with pn=0 returns iv", function()
  local iv = hex_to_bin("fa044b2f42a3fd3b46fb255c")
  local nonce = prot.construct_nonce(iv, 0)
  return assert(nonce == iv, "nonce should equal iv when pn=0")
end)
test("protection: construct_nonce with pn=1", function()
  local iv = hex_to_bin("fa044b2f42a3fd3b46fb255c")
  local nonce = prot.construct_nonce(iv, 1)
  assert(nonce:sub(1, 11) == iv:sub(1, 11), "first 11 bytes should match")
  return assert(string.byte(nonce, 12) == 0x5d, "last byte should be 0x5d")
end)
test("protection: recover_packet_number 1-byte simple", function()
  local pn = prot.recover_packet_number(0, 0, 1)
  return assert(pn == 0, "expected 0, got " .. tostring(pn))
end)
test("protection: recover_packet_number wrap around", function()
  local pn = prot.recover_packet_number(0, 256, 1)
  return assert(pn == 256, "expected 256, got " .. tostring(pn))
end)
test("protection: recover_packet_number lower half wraps back", function()
  local pn = prot.recover_packet_number(5, 130, 1)
  return assert(pn == 5, "expected 5, got " .. tostring(pn))
end)
test("protection: sample_from_packet 16 bytes at correct position", function()
  local pkt = (string.rep("\x00", 20)) .. (string.rep("\xFF", 20))
  local sample = prot.sample_from_packet(pkt, 20)
  assert(#sample == 16, "sample must be 16 bytes")
  return assert(sample == string.rep("\xFF", 16), "sample bytes mismatch")
end)
local ok_backend, backend = pcall(require, "ipparse.lib.crypto.backend.ffi_openssl")
if ok_backend then
  test("protection: AES-128-GCM encrypt/decrypt round-trip", function()
    local key = string.rep("\x01", 16)
    local iv = string.rep("\x02", 12)
    local plain = "Hello, QUIC!"
    local aad = "header"
    local ct = backend.aes_128_gcm_encrypt(key, iv, plain, aad)
    local pt, err = backend.aes_128_gcm_decrypt(key, iv, ct, aad)
    return assert(pt == plain, "round-trip failed: " .. tostring(err))
  end)
  test("protection: AES-128-GCM decrypt fails on bad tag", function()
    local key = string.rep("\x01", 16)
    local iv = string.rep("\x02", 12)
    local ct = backend.aes_128_gcm_encrypt(key, iv, "plaintext", "")
    local bad_ct = ct:sub(1, #ct - 1) .. string.char((string.byte(ct, #ct) + 1) % 256)
    local pt, err = backend.aes_128_gcm_decrypt(key, iv, bad_ct, "")
    assert(pt == nil, "expected nil on bad tag")
    return assert(err ~= nil, "expected error message")
  end)
  test("protection: AES-128-ECB block NIST vector", function()
    local key = hex_to_bin("2b7e151628aed2a6abf7158809cf4f3c")
    local block = hex_to_bin("3243f6a8885a308d313198a2e0370734")
    local out = backend.aes_128_ecb_block(key, block)
    local expected_hex = "3925841d02dc09fbdc118597196a0b32"
    return assert(bin2hex(out) == expected_hex, "AES-ECB NIST mismatch:\ngot: " .. tostring(bin2hex(out)))
  end)
  test("protection: construct_nonce matches RFC 9001 §A.3", function()
    local iv = hex_to_bin("fa044b2f42a3fd3b46fb255c")
    local nonce = prot.construct_nonce(iv, 2)
    return assert(bin2hex(nonce) == "fa044b2f42a3fd3b46fb255e", "nonce mismatch: " .. tostring(bin2hex(nonce)))
  end)
  test("protection: remove_header_protection RFC 9001 §A.2 vector", function()
    local hp_key = hex_to_bin("9f50449e04a0e810283a1e9933adedd2")
    local hdr_hex = "c000000001088394c8f03e5157080000449e7b9aec34"
    local ciphertext_hex = "d1b1c98dd7689fb8ec11d242b123dc9b" .. string.rep("00", 16)
    local pkt = hex_to_bin(hdr_hex .. ciphertext_hex)
    local hdr_bytes, pn, pn_len = prot.remove_header_protection(pkt, 19, hp_key, true, 0, backend)
    assert(hdr_bytes[1] == 0xc3, "first byte should be c3, got " .. tostring(string.format('%02x', hdr_bytes[1])))
    assert(pn == 2, "packet number should be 2, got " .. tostring(pn))
    assert(pn_len == 4, "pn_len should be 4, got " .. tostring(pn_len))
    assert(hdr_bytes[19] == 0x00, "pn byte 0 should be 0x00")
    return assert(hdr_bytes[22] == 0x02, "pn byte 3 should be 0x02")
  end)
else
  test("protection: backend tests skipped (libcrypto not available)", function()
    return true
  end)
end
return util.summary("protection")
