local util = require("ipparse.lib.util")
local test
test = util.test
local sp, su
do
  local _obj_0 = require("ipparse.lib.pack_compat")
  sp, su = _obj_0.pack, _obj_0.unpack
end
local quic = require("ipparse.l4.quic")
local v1 = require("ipparse.l4.quic.v1")
local dcid = "\x01\x02\x03\x04\x05\x06\x07\x08"
local build_initial_pkt
build_initial_pkt = function()
  return sp(">B I4 s1 s1 B B B", 0xC0, 1, dcid, "", 0, 1, 0)
end
test("header: parse long header returns table", function()
  local pkt = build_initial_pkt()
  local h, _ = quic.parse(pkt, 1)
  return assert(type(h) == "table", "expected table")
end)
test("header: long_header flag is true", function()
  local pkt = build_initial_pkt()
  local h, _ = quic.parse(pkt, 1)
  return assert(h.long_header == true)
end)
test("header: version parsed correctly", function()
  local pkt = build_initial_pkt()
  local h, _ = quic.parse(pkt, 1)
  return assert(h.version == 1, "expected version 1, got " .. tostring(h.version))
end)
test("header: dst_connection_id parsed correctly", function()
  local pkt = build_initial_pkt()
  local h, _ = quic.parse(pkt, 1)
  return assert(h.dst_connection_id == dcid, "dcid mismatch")
end)
test("header: src_connection_id empty", function()
  local pkt = build_initial_pkt()
  local h, _ = quic.parse(pkt, 1)
  return assert(h.src_connection_id == "", "scid should be empty")
end)
test("header: token is empty for zero token_length", function()
  local pkt = build_initial_pkt()
  local h, _ = quic.parse(pkt, 1)
  return assert(h.token == "" or h.token == nil, "token should be empty")
end)
test("header: pkt_type is 0x00 for Initial", function()
  local pkt = build_initial_pkt()
  local h, _ = quic.parse(pkt, 1)
  return assert(h.pkt_type == 0x00, "expected pkt_type 0x00, got " .. tostring(h.pkt_type))
end)
test("header: pn_off points past fixed fields", function()
  local pkt = build_initial_pkt()
  local h, _ = quic.parse(pkt, 1)
  return assert(h.pn_off == 18, "expected pn_off=18, got " .. tostring(h.pn_off))
end)
test("header: parse short header", function()
  local pkt = "\x40" .. dcid
  local h, _ = quic.parse(pkt, 1, dcid)
  return assert(h.long_header == nil or h.long_header == false, "expected short header")
end)
test("header: parse advances offset correctly", function()
  local pkt = build_initial_pkt()
  local _, off = quic.parse(pkt, 1)
  return assert(off == 18, "expected off=18, got " .. tostring(off))
end)
test("header: split_datagrams returns one packet for one datagram", function()
  local pkt = build_initial_pkt()
  local datagrams, err = quic.split_datagrams(pkt, 1)
  assert(datagrams, "split failed: " .. tostring(err))
  assert(#datagrams == 1, "expected 1 datagram, got " .. tostring(#datagrams))
  return assert(datagrams[1].data == pkt, "single datagram bytes mismatch")
end)
test("header: split_datagrams splits coalesced Initial packets", function()
  local p1 = build_initial_pkt()
  local p2 = build_initial_pkt()
  local coalesced = p1 .. p2
  local datagrams, err = quic.split_datagrams(coalesced, 1)
  assert(datagrams, "split failed: " .. tostring(err))
  assert(#datagrams == 2, "expected 2 datagrams, got " .. tostring(#datagrams))
  assert(datagrams[1].data == p1, "first datagram mismatch")
  return assert(datagrams[2].data == p2, "second datagram mismatch")
end)
test("header: split_datagrams rejects short header payload", function()
  local short_pkt = "\x40" .. dcid
  local datagrams, err = quic.split_datagrams(short_pkt, 1, dcid)
  assert(datagrams == nil, "expected split failure on short header")
  return assert(err and err:find("short header"), "expected short-header error, got " .. tostring(err))
end)
test("header: HEADER_FORM bit accessible via metatable", function()
  local pkt = build_initial_pkt()
  local h, _ = quic.parse(pkt, 1)
  return assert(h.HEADER_FORM == 0x80, "HEADER_FORM should be 0x80")
end)
test("header: FIXED_BIT accessible", function()
  local pkt = build_initial_pkt()
  local h, _ = quic.parse(pkt, 1)
  return assert(h.FIXED_BIT == 0x40, "FIXED_BIT should be 0x40")
end)
return util.summary("header")
