local ffi = require("ffi")
pcall(ffi.cdef, [[  int pipe2(int pipefd[2], int flags);
  int fcntl(int fd, int cmd, ...);
  int close(int fd);
  ssize_t read(int fd, void *buf, size_t count);
  ssize_t write(int fd, const void *buf, size_t count);
  int* __errno_location();
]])
local O_NONBLOCK = 2048
local IP4_RAW = "\xC0\xA8\x01\x2A"
local RESOLVER4_RAW = "\x01\x01\x01\x03"
local MAC_RAW = "\xAA\xBB\xCC\xDD\xEE\xFF"
local TXID = 0x1234
local PORT = 54321
local IP6_RAW = "\x20\x01\x0d\xb8\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"
local RESOLVER6_RAW = "\x20\x01\x0d\xb8\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x53"
local make_pipe
make_pipe = function()
  local pipefd = ffi.new("int[2]")
  local r = ffi.C.pipe2(pipefd, O_NONBLOCK)
  assert(r == 0, "pipe2 a échoué")
  return {
    pipefd[0],
    pipefd[1]
  }
end
local close_pipe
close_pipe = function(p)
  ffi.C.close(p[1])
  return ffi.C.close(p[2])
end
local fresh_ipc
fresh_ipc = function()
  package.loaded["ipc"] = nil
  return dofile("lua/ipc.lua")
end
return describe("ipc", function()
  describe("encode/decode IPv4 round-trip", function()
    return it("round-trip complet avec MAC", function()
      local m_ipc = fresh_ipc()
      local msg = m_ipc.encode_msg(TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW)
      local decoded = m_ipc.decode_msg(msg)
      assert.equals(TXID, decoded.txid)
      assert.equals(PORT, decoded.src_port)
      assert.equals("192.168.1.42", decoded.ip_str)
      assert.equals("1.1.1.3", decoded.resolver_ip_str)
      assert.equals(0x41, decoded.msg_type)
      assert.equals("aa:bb:cc:dd:ee:ff", decoded.mac_str)
      assert.is_true(decoded.ipv4)
      return assert.is_false(decoded.refused)
    end)
  end)
  describe("encode/decode IPv4 sans MAC", function()
    return it("mac nil → 00:00:00:00:00:00", function()
      local m_ipc = fresh_ipc()
      local msg = m_ipc.encode_msg(0x1234, "\xC0\xA8\x01\x2A", 54321, nil, "\x01\x01\x01\x01")
      local decoded = m_ipc.decode_msg(msg)
      assert.equals("1.1.1.1", decoded.resolver_ip_str)
      return assert.equals("00:00:00:00:00:00", decoded.mac_str)
    end)
  end)
  describe("encode/decode IPv6 round-trip", function()
    return it("round-trip avec adresses IPv6", function()
      local m_ipc = fresh_ipc()
      local msg = m_ipc.encode_msg(0xABCD, IP6_RAW, 5353, "\x00\x11\x22\x33\x44\x55", RESOLVER6_RAW)
      local decoded = m_ipc.decode_msg(msg)
      assert.equals("2001:db8::1", decoded.ip_str)
      assert.equals("2001:db8::53", decoded.resolver_ip_str)
      assert.equals(0x36, decoded.msg_type)
      assert.is_false(decoded.ipv4)
      return assert.is_false(decoded.refused)
    end)
  end)
  describe("make_key", function()
    return it("des paramètres différents donnent des clés différentes", function()
      local m_ipc = fresh_ipc()
      local k1 = m_ipc.make_key(0x1234, "192.168.1.1", 53, "1.1.1.1")
      local k2 = m_ipc.make_key(0x1234, "192.168.1.2", 53, "1.1.1.1")
      local k3 = m_ipc.make_key(0x5678, "192.168.1.1", 53, "1.1.1.1")
      local k4 = m_ipc.make_key(0x1234, "192.168.1.1", 53, "1.1.1.3")
      assert.not_equals(k1, k2)
      assert.not_equals(k1, k3)
      return assert.not_equals(k1, k4)
    end)
  end)
  describe("drain_pipe", function()
    return it("écrit write_msg, drain_pipe absorbe le message et is_pending est vrai", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      local ok = m_ipc.write_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW)
      assert.is_true(ok)
      local now_t = 1000
      local count = m_ipc.drain_pipe(rfd, (function()
        return now_t
      end), nil)
      assert.equals(1, count)
      local pending = m_ipc.is_pending(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return now_t + 1
      end)
      assert.is_true(pending)
      return close_pipe(p)
    end)
  end)
  describe("expiration de token", function()
    return it("valide à t+4, expiré à t+6 (TTL=5)", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      local base = 0
      m_ipc.write_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW)
      m_ipc.drain_pipe(rfd, (function()
        return base
      end), nil)
      assert.is_true(m_ipc.is_pending(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return base + 4
      end))
      assert.is_false(m_ipc.is_pending(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return base + 6
      end))
      return close_pipe(p)
    end)
  end)
  describe("MSG_IPV4_REFUSED", function()
    return it("msg_type == 0x52 et refused == true", function()
      local m_ipc = fresh_ipc()
      local msg = m_ipc.encode_msg(TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, true)
      local decoded = m_ipc.decode_msg(msg)
      assert.equals(0x52, decoded.msg_type)
      return assert.is_true(decoded.refused)
    end)
  end)
  describe("MSG_IPV6_REFUSED", function()
    return it("refused=true et ipv4=false pour une adresse IPv6", function()
      local m_ipc = fresh_ipc()
      local msg = m_ipc.encode_msg(0xABCD, IP6_RAW, 5353, "\x00\x11\x22\x33\x44\x55", RESOLVER6_RAW, true)
      local decoded = m_ipc.decode_msg(msg)
      assert.equals(0x72, decoded.msg_type)
      assert.is_true(decoded.refused)
      return assert.is_false(decoded.ipv4)
    end)
  end)
  describe("registre dynamique de modificateurs", function()
    it("register_modifier + encode_modifiers + decode_modifiers round-trip", function()
      local m_ipc = fresh_ipc()
      m_ipc.register_modifier("foo")
      m_ipc.register_modifier("bar")
      local bits = m_ipc.encode_modifiers({
        foo = true,
        bar = false
      })
      assert.is_true(bits > 0, "foo=true → bitmask non nul")
      local mods = m_ipc.decode_modifiers(bits)
      assert.is_true(mods.foo, "foo décodé à true")
      return assert.is_false(mods.bar, "bar décodé à false")
    end)
    it("modifier_bit retourne 0 pour un nom inconnu", function()
      local m_ipc = fresh_ipc()
      return assert.equals(0, m_ipc.modifier_bit("unknown_mod"))
    end)
    return it("deux modificateurs ont des bits distincts", function()
      local m_ipc = fresh_ipc()
      m_ipc.register_modifier("alpha")
      m_ipc.register_modifier("beta")
      local ba = m_ipc.modifier_bit("alpha")
      local bb = m_ipc.modifier_bit("beta")
      assert.is_true(ba > 0)
      assert.is_true(bb > 0)
      return assert.not_equals(ba, bb)
    end)
  end)
  describe("modificateur via pipe", function()
    return it("write_msg + modifiers → entry.modifiers décodé", function()
      local m_ipc = fresh_ipc()
      m_ipc.register_modifier("dnsonly")
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.write_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, "reason", nil, nil, nil, {
        dnsonly = true
      })
      m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      local entry = m_ipc.get_pending_entry(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return 1
      end)
      assert.is_not_nil(entry)
      assert.is_false(entry.refused)
      assert.is_true(entry.modifiers.dnsonly, "dnsonly transmis dans modifiers")
      return close_pipe(p)
    end)
  end)
  describe("write_refused_msg via pipe", function()
    return it("drain_pipe stocke un entry avec refused=true", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.write_refused_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW)
      m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      local entry = m_ipc.get_pending_entry(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return 1
      end)
      assert.is_not_nil(entry)
      assert.is_true(entry.refused)
      return close_pipe(p)
    end)
  end)
  describe("reason round-trip", function()
    return it("reason est préservée après encode + decode", function()
      local m_ipc = fresh_ipc()
      local reason = "blocked by policy"
      local msg = m_ipc.encode_msg(TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, false, reason)
      local decoded = m_ipc.decode_msg(msg)
      assert.is_not_nil(decoded.reason)
      return assert.truthy(decoded.reason:find("blocked", 1, true))
    end)
  end)
  describe("rule_id + timeout round-trip", function()
    return it("préserve rule_id et timeout", function()
      local m_ipc = fresh_ipc()
      local msg = m_ipc.encode_msg(TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, false, "allowed", 17, "dns_workhours", "240s")
      local decoded = m_ipc.decode_msg(msg)
      assert.equals("dns_workhours", decoded.rule_id)
      return assert.equals("240s", decoded.timeout)
    end)
  end)
  describe("reason troncature", function()
    return it("reason de 70 chars est tronquée à 63", function()
      local m_ipc = fresh_ipc()
      local long_r = string.rep("x", 70)
      local msg = m_ipc.encode_msg(TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, false, long_r)
      local decoded = m_ipc.decode_msg(msg)
      return assert.equals(63, #decoded.reason)
    end)
  end)
  describe("write_refused_msg + reason", function()
    return it("entry.reason est préservée après drain_pipe", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.write_refused_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, "policy block")
      m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      local entry = m_ipc.get_pending_entry(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return 1
      end)
      assert.is_not_nil(entry)
      assert.equals("policy block", entry.reason)
      return close_pipe(p)
    end)
  end)
  describe("reason absente", function()
    return it("entry.reason est vide quand aucune reason n'est fournie", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.write_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW)
      m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      local entry = m_ipc.get_pending_entry(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return 1
      end)
      assert.is_not_nil(entry)
      assert.truthy(entry.reason == nil or entry.reason == "")
      return close_pipe(p)
    end)
  end)
  describe("write_msg + reason", function()
    return it("entry.reason est préservée pour un message normal", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.write_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, "custom reason")
      m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      local entry = m_ipc.get_pending_entry(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return 1
      end)
      assert.is_not_nil(entry)
      assert.equals("custom reason", entry.reason)
      return close_pipe(p)
    end)
  end)
  describe("write_msg + reason + modifier", function()
    return it("reason et modifier sont préservés dans l'entrée pending", function()
      local m_ipc = fresh_ipc()
      m_ipc.register_modifier("dnsonly")
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.write_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, "dnsonly reason", nil, nil, nil, {
        dnsonly = true
      })
      m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      local entry = m_ipc.get_pending_entry(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return 1
      end)
      assert.is_not_nil(entry)
      assert.equals("dnsonly reason", entry.reason)
      assert.is_true(entry.modifiers.dnsonly)
      return close_pipe(p)
    end)
  end)
  describe("decode_msg trop court", function()
    return it("message trop court → nil", function()
      local m_ipc = fresh_ipc()
      local result = m_ipc.decode_msg("toocourt")
      return assert.is_nil(result)
    end)
  end)
  describe("encode_msg avec benchmark_ms", function()
    return it("benchmark_ms encodé et décodé", function()
      local m_ipc = fresh_ipc()
      local msg = m_ipc.encode_msg(TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, false, "", 42, "rule_dns", "90s")
      assert.is_true(#msg > 0)
      local decoded = m_ipc.decode_msg(msg)
      assert.is_not_nil(decoded)
      assert.equals(TXID, decoded.txid)
      assert.equals(42, decoded.benchmark_ms)
      assert.equals("rule_dns", decoded.rule_id)
      return assert.equals("90s", decoded.timeout)
    end)
  end)
  describe("write_msg fd invalide", function()
    return it("write_msg sur fd -1 ne crash pas", function()
      local m_ipc = fresh_ipc()
      local ok, err = pcall(function()
        return m_ipc.write_msg(-1, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW)
      end)
      return assert.is_true((ok == true or ok == false))
    end)
  end)
  describe("drain_pipe pipe vide (EAGAIN)", function()
    return it("drain_pipe sur pipe vide retourne 0 sans erreur", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      local count = m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      assert.equals(0, count, "aucun message absorbé sur pipe vide")
      return close_pipe(p)
    end)
  end)
  describe("is_pending clé absente", function()
    return it("is_pending retourne false pour une clé inexistante", function()
      local m_ipc = fresh_ipc()
      local result = m_ipc.is_pending(0xDEAD, "1.2.3.4", 1234, "5.6.7.8", function()
        return 0
      end)
      return assert.is_false(result, "is_pending doit retourner false si clé absente")
    end)
  end)
  describe("get_pending_entry clé absente", function()
    return it("get_pending_entry retourne nil pour une clé inexistante", function()
      local m_ipc = fresh_ipc()
      local entry = m_ipc.get_pending_entry(0xDEAD, "1.2.3.4", 1234, "5.6.7.8", function()
        return 0
      end)
      return assert.is_nil(entry, "get_pending_entry doit retourner nil si clé absente")
    end)
  end)
  describe("get_pending_entry expirée", function()
    return it("get_pending_entry retourne nil après expiration", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      local base = 0
      m_ipc.write_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW)
      m_ipc.drain_pipe(rfd, (function()
        return base
      end), nil)
      local e1 = m_ipc.get_pending_entry(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return base + 4
      end)
      assert.is_not_nil(e1, "entrée présente avant expiration")
      local e2 = m_ipc.get_pending_entry(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return base + 100
      end)
      assert.is_nil(e2, "get_pending_entry nil après expiration")
      return close_pipe(p)
    end)
  end)
  describe("consume", function()
    return it("consume supprime l'entrée et is_pending retourne false", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.write_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW)
      m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      assert.is_true(m_ipc.is_pending(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return 1
      end))
      m_ipc.consume(TXID, "192.168.1.42", PORT, "1.1.1.3")
      assert.is_false(m_ipc.is_pending(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return 1
      end))
      return close_pipe(p)
    end)
  end)
  describe("drain_pipe on_msg callback", function()
    return it("on_msg est appelé pour chaque message absorbé", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.register_modifier("dnsonly")
      m_ipc.write_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, "reason A")
      m_ipc.write_msg(wfd, 0x5678, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, nil, nil, nil, nil, {
        dnsonly = true
      })
      local msgs = { }
      local count = m_ipc.drain_pipe(rfd, (function()
        return 0
      end), function(msg)
        msgs[#msgs + 1] = msg
      end)
      assert.equals(2, count, "2 messages absorbés")
      assert.equals(2, #msgs, "on_msg appelé 2 fois")
      assert.equals(TXID, msgs[1].txid)
      assert.equals("reason A", msgs[1].reason)
      assert.is_true(msgs[2].modifiers.dnsonly)
      return close_pipe(p)
    end)
  end)
  describe("encode_msg benchmark_ms round-trip", function()
    return it("benchmark_ms est encodé et décodé correctement", function()
      local m_ipc = fresh_ipc()
      local bms = 12345
      local msg = m_ipc.encode_msg(TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, false, "", bms)
      local decoded = m_ipc.decode_msg(msg)
      assert.is_not_nil(decoded)
      return assert.equals(bms, decoded.benchmark_ms, "benchmark_ms préservé")
    end)
  end)
  describe("reason 63 chars (limite exacte)", function()
    return it("reason de 63 chars n'est pas tronquée", function()
      local m_ipc = fresh_ipc()
      local reason63 = string.rep("y", 63)
      local msg = m_ipc.encode_msg(TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, false, reason63)
      local decoded = m_ipc.decode_msg(msg)
      assert.equals(63, #decoded.reason, "longueur préservée")
      return assert.equals(reason63, decoded.reason, "contenu intact")
    end)
  end)
  describe("decode_msg trop court", function()
    return it("decode_msg sur chaîne courte retourne nil", function()
      local m_ipc = fresh_ipc()
      local result = m_ipc.decode_msg("too_short")
      return assert.is_nil(result, "decode_msg doit retourner nil si < 115 B")
    end)
  end)
  describe("modificateur IPv6 round-trip via drain_pipe", function()
    return it("write_msg IPv6 + modifier dnsonly → entry.modifiers.dnsonly = true", function()
      local m_ipc = fresh_ipc()
      m_ipc.register_modifier("dnsonly")
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.write_msg(wfd, TXID, IP6_RAW, PORT, MAC_RAW, RESOLVER6_RAW, "ipv6 dns", nil, nil, nil, {
        dnsonly = true
      })
      local count = m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      assert.equals(1, count)
      local entry = m_ipc.get_pending_entry(TXID, "2001:db8::1", PORT, "2001:db8::53", function()
        return 1
      end)
      assert.is_not_nil(entry, "entrée présente")
      assert.is_true(entry.modifiers.dnsonly, "dnsonly=true pour IPv6")
      assert.equals("ipv6 dns", entry.reason)
      return close_pipe(p)
    end)
  end)
  return describe("IPv6 refused round-trip via drain_pipe", function()
    return it("write_refused_msg IPv6 → drain_pipe → entry.refused = true", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.write_refused_msg(wfd, TXID, IP6_RAW, PORT, MAC_RAW, RESOLVER6_RAW, "ipv6 block")
      local count = m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      assert.equals(1, count)
      local entry = m_ipc.get_pending_entry(TXID, "2001:db8::1", PORT, "2001:db8::53", function()
        return 1
      end)
      assert.is_not_nil(entry, "entrée présente")
      assert.is_true(entry.refused, "refused=true pour IPv6")
      assert.equals("ipv6 block", entry.reason)
      return close_pipe(p)
    end)
  end)
end)
