local ffi = require("ffi")
pcall(ffi.cdef, [[  int pipe2(int pipefd[2], int flags);
  int fcntl(int fd, int cmd, ...);
  int close(int fd);
  ssize_t read(int fd, void *buf, size_t count);
  ssize_t write(int fd, const void *buf, size_t count);
  int* __errno_location();
]])
local O_NONBLOCK = 2048
local IP4_RAW = "\xC0\xA8\x01\x2A"
local RESOLVER4_RAW = "\x01\x01\x01\x03"
local MAC_RAW = "\xAA\xBB\xCC\xDD\xEE\xFF"
local TXID = 0x1234
local PORT = 54321
local IP6_RAW = "\x20\x01\x0d\xb8\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"
local RESOLVER6_RAW = "\x20\x01\x0d\xb8\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x53"
local make_pipe
make_pipe = function()
  local pipefd = ffi.new("int[2]")
  local r = ffi.C.pipe2(pipefd, O_NONBLOCK)
  assert(r == 0, "pipe2 a échoué")
  return {
    pipefd[0],
    pipefd[1]
  }
end
local close_pipe
close_pipe = function(p)
  ffi.C.close(p[1])
  return ffi.C.close(p[2])
end
local fresh_ipc
fresh_ipc = function()
  package.loaded["ipc"] = nil
  return dofile("lua/ipc.lua")
end
return describe("ipc", function()
  describe("encode/decode IPv4 round-trip", function()
    return it("round-trip complet avec MAC", function()
      local m_ipc = fresh_ipc()
      local msg = m_ipc.encode_msg(TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW)
      local decoded = m_ipc.decode_msg(msg)
      assert.equals(TXID, decoded.txid)
      assert.equals(PORT, decoded.src_port)
      assert.equals("192.168.1.42", decoded.ip_str)
      assert.equals("1.1.1.3", decoded.resolver_ip_str)
      assert.equals(0x41, decoded.msg_type)
      assert.equals("aa:bb:cc:dd:ee:ff", decoded.mac_str)
      assert.is_true(decoded.ipv4)
      assert.is_false(decoded.refused)
      return assert.is_false(decoded.dnsonly)
    end)
  end)
  describe("encode/decode IPv4 sans MAC", function()
    return it("mac nil → 00:00:00:00:00:00", function()
      local m_ipc = fresh_ipc()
      local msg = m_ipc.encode_msg(0x1234, "\xC0\xA8\x01\x2A", 54321, nil, "\x01\x01\x01\x01")
      local decoded = m_ipc.decode_msg(msg)
      assert.equals("1.1.1.1", decoded.resolver_ip_str)
      return assert.equals("00:00:00:00:00:00", decoded.mac_str)
    end)
  end)
  describe("encode/decode IPv6 round-trip", function()
    return it("round-trip avec adresses IPv6", function()
      local m_ipc = fresh_ipc()
      local msg = m_ipc.encode_msg(0xABCD, IP6_RAW, 5353, "\x00\x11\x22\x33\x44\x55", RESOLVER6_RAW)
      local decoded = m_ipc.decode_msg(msg)
      assert.equals("2001:db8::1", decoded.ip_str)
      assert.equals("2001:db8::53", decoded.resolver_ip_str)
      assert.equals(0x36, decoded.msg_type)
      assert.is_false(decoded.ipv4)
      assert.is_false(decoded.refused)
      return assert.is_false(decoded.dnsonly)
    end)
  end)
  describe("make_key", function()
    return it("des paramètres différents donnent des clés différentes", function()
      local m_ipc = fresh_ipc()
      local k1 = m_ipc.make_key(0x1234, "192.168.1.1", 53, "1.1.1.1")
      local k2 = m_ipc.make_key(0x1234, "192.168.1.2", 53, "1.1.1.1")
      local k3 = m_ipc.make_key(0x5678, "192.168.1.1", 53, "1.1.1.1")
      local k4 = m_ipc.make_key(0x1234, "192.168.1.1", 53, "1.1.1.3")
      assert.not_equals(k1, k2)
      assert.not_equals(k1, k3)
      return assert.not_equals(k1, k4)
    end)
  end)
  describe("drain_pipe", function()
    return it("écrit write_msg, drain_pipe absorbe le message et is_pending est vrai", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      local ok = m_ipc.write_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW)
      assert.is_true(ok)
      local now_t = 1000
      local count = m_ipc.drain_pipe(rfd, (function()
        return now_t
      end), nil)
      assert.equals(1, count)
      local pending = m_ipc.is_pending(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return now_t + 1
      end)
      assert.is_true(pending)
      return close_pipe(p)
    end)
  end)
  describe("expiration de token", function()
    return it("valide à t+4, expiré à t+6 (TTL=5)", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      local base = 0
      m_ipc.write_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW)
      m_ipc.drain_pipe(rfd, (function()
        return base
      end), nil)
      assert.is_true(m_ipc.is_pending(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return base + 4
      end))
      assert.is_false(m_ipc.is_pending(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return base + 6
      end))
      return close_pipe(p)
    end)
  end)
  describe("MSG_IPV4_REFUSED", function()
    return it("msg_type == 0x52 et refused == true", function()
      local m_ipc = fresh_ipc()
      local msg = m_ipc.encode_msg(TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, true, false)
      local decoded = m_ipc.decode_msg(msg)
      assert.equals(0x52, decoded.msg_type)
      assert.is_true(decoded.refused)
      return assert.is_false(decoded.dnsonly)
    end)
  end)
  describe("MSG_IPV6_REFUSED", function()
    return it("refused=true et ipv4=false pour une adresse IPv6", function()
      local m_ipc = fresh_ipc()
      local msg = m_ipc.encode_msg(0xABCD, IP6_RAW, 5353, "\x00\x11\x22\x33\x44\x55", RESOLVER6_RAW, true, false)
      local decoded = m_ipc.decode_msg(msg)
      assert.equals(0x72, decoded.msg_type)
      assert.is_true(decoded.refused)
      return assert.is_false(decoded.ipv4)
    end)
  end)
  describe("MSG_IPV4_DNSONLY", function()
    return it("msg_type == 0x44 et dnsonly == true", function()
      local m_ipc = fresh_ipc()
      local msg = m_ipc.encode_msg(TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, false, true)
      local decoded = m_ipc.decode_msg(msg)
      assert.equals(0x44, decoded.msg_type)
      assert.is_true(decoded.dnsonly)
      return assert.is_false(decoded.refused)
    end)
  end)
  describe("MSG_IPV6_DNSONLY", function()
    return it("msg_type == 0x64 et dnsonly == true pour IPv6", function()
      local m_ipc = fresh_ipc()
      local msg = m_ipc.encode_msg(0xABCD, IP6_RAW, 5353, "\x00\x11\x22\x33\x44\x55", RESOLVER6_RAW, false, true)
      local decoded = m_ipc.decode_msg(msg)
      assert.equals(0x64, decoded.msg_type)
      assert.is_true(decoded.dnsonly)
      return assert.is_false(decoded.refused)
    end)
  end)
  describe("write_dnsonly_msg via pipe", function()
    return it("drain_pipe stocke un entry avec dnsonly=true", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.write_dnsonly_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW)
      m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      local entry = m_ipc.get_pending_entry(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return 1
      end)
      assert.is_not_nil(entry)
      assert.is_true(entry.dnsonly)
      assert.is_false(entry.refused)
      return close_pipe(p)
    end)
  end)
  describe("write_refused_msg via pipe", function()
    return it("drain_pipe stocke un entry avec refused=true", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.write_refused_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW)
      m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      local entry = m_ipc.get_pending_entry(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return 1
      end)
      assert.is_not_nil(entry)
      assert.is_true(entry.refused)
      assert.is_false(entry.dnsonly)
      return close_pipe(p)
    end)
  end)
  describe("reason round-trip", function()
    return it("reason est préservée après encode + decode", function()
      local m_ipc = fresh_ipc()
      local reason = "blocked by policy"
      local msg = m_ipc.encode_msg(TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, false, false, reason)
      local decoded = m_ipc.decode_msg(msg)
      assert.is_not_nil(decoded.reason)
      return assert.truthy(decoded.reason:find("blocked", 1, true))
    end)
  end)
  describe("reason troncature", function()
    return it("reason de 70 chars est tronquée à 63", function()
      local m_ipc = fresh_ipc()
      local long_r = string.rep("x", 70)
      local msg = m_ipc.encode_msg(TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, false, false, long_r)
      local decoded = m_ipc.decode_msg(msg)
      return assert.equals(63, #decoded.reason)
    end)
  end)
  describe("write_refused_msg + reason", function()
    return it("entry.reason est préservée après drain_pipe", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.write_refused_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, "policy block")
      m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      local entry = m_ipc.get_pending_entry(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return 1
      end)
      assert.is_not_nil(entry)
      assert.equals("policy block", entry.reason)
      return close_pipe(p)
    end)
  end)
  describe("reason absente", function()
    return it("entry.reason est vide quand aucune reason n'est fournie", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.write_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW)
      m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      local entry = m_ipc.get_pending_entry(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return 1
      end)
      assert.is_not_nil(entry)
      assert.truthy(entry.reason == nil or entry.reason == "")
      return close_pipe(p)
    end)
  end)
  describe("write_msg + reason", function()
    return it("entry.reason est préservée pour un message normal", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.write_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, "custom reason")
      m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      local entry = m_ipc.get_pending_entry(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return 1
      end)
      assert.is_not_nil(entry)
      assert.equals("custom reason", entry.reason)
      return close_pipe(p)
    end)
  end)
  return describe("write_dnsonly_msg + reason", function()
    return it("entry.reason est préservée pour un message dnsonly", function()
      local m_ipc = fresh_ipc()
      local p = make_pipe()
      local rfd, wfd = p[1], p[2]
      m_ipc.write_dnsonly_msg(wfd, TXID, IP4_RAW, PORT, MAC_RAW, RESOLVER4_RAW, "dnsonly reason")
      m_ipc.drain_pipe(rfd, (function()
        return 0
      end), nil)
      local entry = m_ipc.get_pending_entry(TXID, "192.168.1.42", PORT, "1.1.1.3", function()
        return 1
      end)
      assert.is_not_nil(entry)
      assert.equals("dnsonly reason", entry.reason)
      return close_pipe(p)
    end)
  end)
end)
