local util = require("ipparse.lib.util")
local test
test = util.test
local dns = require("ipparse.l7.dns")
local hex2bin
hex2bin = require("ipparse.init").hex2bin
local dns_query = hex2bin("123401000001000000000000076578616d706c6503636f6d0000010001")
local dns_response = hex2bin("123481800001000100000000" .. "076578616d706c6503636f6d00" .. "00010001" .. "c00c" .. "00010001" .. "00000e10" .. "0004" .. "5db8d822")
local dns_loop_pointer = hex2bin("000101000001000000000000" .. "c00c" .. "00010001")
local dns_truncated_label = hex2bin("000101000001000000000000" .. "056162")
test("parse_header extracts id", function()
  local header, _ = dns.parse_header(dns_query, 1, false)
  assert(header ~= nil, "parse_header should not return nil")
  return assert(header.id == 0x1234, "id should be 0x1234, got " .. tostring(header.id))
end)
test("parse_header extracts qdcount", function()
  local header, _ = dns.parse_header(dns_query, 1, false)
  return assert(header.qdcount == 1, "qdcount should be 1, got " .. tostring(header.qdcount))
end)
test("header rd flag is set", function()
  local header, _ = dns.parse_header(dns_query, 1, false)
  return assert(header.rd == true, "rd flag should be true")
end)
test("header qr flag is false for query", function()
  local header, _ = dns.parse_header(dns_query, 1, false)
  return assert(header.qr == false, "qr should be false for a query")
end)
test("parse returns question name", function()
  local msg, _ = dns.parse(dns_query, 1, false)
  assert(msg ~= nil, "parse should not return nil")
  assert(msg.question ~= nil, "question should not be nil")
  return assert(msg.question.name == "example.com", "question name should be 'example.com', got '" .. tostring(msg.question.name) .. "'")
end)
test("question qtype is A", function()
  local msg, _ = dns.parse(dns_query, 1, false)
  return assert(dns.types[msg.question.qtype] == "A", "qtype should be A, got '" .. tostring(dns.types[msg.question.qtype]) .. "'")
end)
test("question qclass is IN", function()
  local msg, _ = dns.parse(dns_query, 1, false)
  return assert(dns.classes[msg.question.qclass] == "IN", "qclass should be IN, got '" .. tostring(dns.classes[msg.question.qclass]) .. "'")
end)
test("parse response: header qr flag is true", function()
  local msg, _ = dns.parse(dns_response, 1, false)
  return assert(msg.header.qr == true, "qr should be true for a response")
end)
test("parse response: header ra flag is true", function()
  local msg, _ = dns.parse(dns_response, 1, false)
  return assert(msg.header.ra == true, "ra flag should be true")
end)
test("parse response: ancount == 1", function()
  local msg, _ = dns.parse(dns_response, 1, false)
  return assert(msg.header.ancount == 1, "ancount should be 1, got " .. tostring(msg.header.ancount))
end)
test("label compression: answer name is example.com", function()
  local msg, _ = dns.parse(dns_response, 1, false)
  assert(#msg.answers >= 1, "should have at least 1 answer")
  return assert(msg.answers[1].name == "example.com", "answer name should be 'example.com', got '" .. tostring(msg.answers[1].name) .. "'")
end)
test("answer rtype is A", function()
  local msg, _ = dns.parse(dns_response, 1, false)
  return assert(dns.types[msg.answers[1].rtype] == "A", "answer rtype should be A")
end)
test("answer rclass is IN", function()
  local msg, _ = dns.parse(dns_response, 1, false)
  return assert(dns.classes[msg.answers[1].rclass] == "IN", "answer rclass should be IN")
end)
test("answer ttl is 3600", function()
  local msg, _ = dns.parse(dns_response, 1, false)
  return assert(msg.answers[1].ttl == 3600, "ttl should be 3600, got " .. tostring(msg.answers[1].ttl))
end)
test("answer rdata is 93.184.216.34", function()
  local msg, _ = dns.parse(dns_response, 1, false)
  return assert(msg.answers[1].rdata == "\x5d\xb8\xd8\x22", "rdata mismatch")
end)
test("types bidirectional: types[1] == 'A'", function()
  return assert(dns.types[1] == "A", "types[1] should be 'A', got '" .. tostring(dns.types[1]) .. "'")
end)
test("types bidirectional: types['A'] == 1", function()
  return assert(dns.types["A"] == 1, "types['A'] should be 1, got " .. tostring(dns.types['A']))
end)
test("classes bidirectional: classes[1] == 'IN'", function()
  return assert(dns.classes[1] == "IN", "classes[1] should be 'IN', got '" .. tostring(dns.classes[1]) .. "'")
end)
test("classes bidirectional: classes['IN'] == 1", function()
  return assert(dns.classes["IN"] == 1, "classes['IN'] should be 1, got " .. tostring(dns.classes['IN']))
end)
test("parse fails safely on compression pointer loop", function()
  local msg, _, err = dns.parse(dns_loop_pointer, 1, false)
  assert(msg == nil, "expected parse failure")
  return assert(err and err:match("loop"), "expected pointer loop error, got " .. tostring(err))
end)
test("parse fails safely on truncated label", function()
  local msg, _, err = dns.parse(dns_truncated_label, 1, false)
  assert(msg == nil, "expected parse failure")
  return assert(err and err:match("truncated DNS label"), "expected truncated label error, got " .. tostring(err))
end)
return util.summary("l7/dns")
