local ffi = require("ffi")
local bit = require("bit")
pcall(function()
  return ffi.cdef("typedef void sig_fn_t(int);")
end)
pcall(function()
  return ffi.cdef("sig_fn_t *signal(int, sig_fn_t *);")
end)
pcall(function()
  return ffi.cdef("int raise(int sig);")
end)
pcall(function()
  return ffi.cdef("unsigned int alarm(unsigned int seconds);")
end)
local SIGALRM = 14
local ITIMER_REAL = 0
local socket = require("lib.socket")
pcall(function()
  return ffi.cdef([[  struct itimerval {
    struct timeval it_interval;
    struct timeval it_value;
  };
  int setitimer(int which, const struct itimerval *new_value, struct itimerval *old_value);
]])
end)
describe("lib.socket création", function()
  it("crée un socket TCP IPv4", function()
    local srv = socket.tcp()
    assert.is_not_nil(srv)
    assert.equals(2, srv.family)
    assert.is_false(srv.closed)
    return srv:close()
  end)
  return it("le socket est marqué closed après close()", function()
    local srv = socket.tcp()
    srv:close()
    return assert.is_true(srv.closed)
  end)
end)
describe("lib.socket accept() cas normaux", function()
  it("retourne nil (EAGAIN) quand aucune connexion n'est en attente", function()
    local srv = socket.tcp()
    srv:bind("127.0.0.1", 0)
    srv:settimeout(0.1)
    local client = srv:accept()
    assert.is_nil(client)
    return srv:close()
  end)
  return it("accepte une connexion réelle et retourne un socket client valide", function()
    local srv = socket.tcp()
    srv:bind("127.0.0.1", 0)
    srv:settimeout(0.5)
    local addr4 = ffi.new("struct sockaddr_in")
    local addrlen = ffi.new("socklen_t[1]")
    addrlen[0] = ffi.sizeof(addr4)
    ffi.C.getsockname(srv.fd, ffi.cast("struct sockaddr*", addr4), addrlen)
    local port = ffi.C.ntohs(addr4.sin_port)
    local cli = socket.tcp()
    cli:settimeout(0.5)
    pcall(function()
      return cli:connect("127.0.0.1", port)
    end)
    local client = srv:accept()
    assert.is_not_nil(client)
    assert.is_false(client.closed)
    client:close()
    cli:close()
    return srv:close()
  end)
end)
describe("lib.socket accept() erreurs non fatales", function()
  it("lève une erreur sur EBADF (fd déjà fermé) — erreur FATALE", function()
    local srv = socket.tcp()
    srv:close()
    local ok, err = pcall(function()
      return srv:accept()
    end)
    assert.is_false(ok)
    return assert.is_string(err)
  end)
  it("retourne nil sur EAGAIN / EWOULDBLOCK (errno=11) — non fatal", function()
    local srv = socket.tcp()
    srv:bind("127.0.0.1", 0)
    srv:settimeout(0.1)
    local client = srv:accept()
    srv:close()
    return assert.is_nil(client)
  end)
  return it("EINTR (errno=4) et ECONNABORTED (errno=103) sont dans les cas non-fatals", function()
    local fh = io.open("lua/lib/socket.lua", "r")
    assert.is_not_nil(fh, "lua/lib/socket.lua doit exister (compilé)")
    local source = fh:read("*a")
    fh:close()
    assert.truthy((source:find("errno == 4")), "EINTR (errno=4) doit être géré dans accept()")
    return assert.truthy((source:find("errno == 103")), "ECONNABORTED (errno=103) doit être géré dans accept()")
  end)
end)
describe("lib.socket socket_select EINTR", function()
  it("socket_select retourne des tables sur timeout normal (pas d'exception)", function()
    local srv = socket.tcp()
    srv:bind("127.0.0.1", 0)
    local ok, ready = pcall(socket.socket_select, {
      srv
    }, nil, 0.01)
    srv:close()
    assert.is_true(ok, "socket_select ne doit pas lever d'exception")
    assert.is_table(ready)
    return assert.equals(0, #ready)
  end)
  it("retourne {},{} au lieu de planter quand select() est interrompu par SIGALRM", function()
    local noop_handler = ffi.cast("sig_fn_t*", function() end)
    ffi.C.signal(SIGALRM, noop_handler)
    local timer = ffi.new("struct itimerval")
    timer.it_value.tv_sec = 0
    timer.it_value.tv_usec = 100000
    ffi.C.setitimer(ITIMER_REAL, timer, nil)
    local srv = socket.tcp()
    srv:bind("127.0.0.1", 0)
    local ok, result = pcall(socket.socket_select, {
      srv
    }, nil, 5.0)
    timer.it_value.tv_usec = 0
    ffi.C.setitimer(ITIMER_REAL, timer, nil)
    ffi.C.signal(SIGALRM, ffi.cast("sig_fn_t*", ffi.cast("void*", 0)))
    srv:close()
    assert.is_true(ok, "socket_select ne doit pas planter sur EINTR")
    return assert.is_table(result)
  end)
  return it("contient le traitement EINTR dans le source compilé", function()
    local fh = io.open("lua/lib/socket.lua", "r")
    assert.is_not_nil(fh)
    local source = fh:read("*a")
    fh:close()
    return assert.truthy((source:find("errno == 4")), "EINTR (errno=4) doit être géré dans socket_select")
  end)
end)
return describe("lib.socket socket_select comportement nominal", function()
  return it("détecte un socket lisible quand une connexion est en attente", function()
    local srv = socket.tcp()
    srv:bind("127.0.0.1", 0)
    srv:settimeout(0.5)
    local addr4 = ffi.new("struct sockaddr_in")
    local addrlen = ffi.new("socklen_t[1]")
    addrlen[0] = ffi.sizeof(addr4)
    ffi.C.getsockname(srv.fd, ffi.cast("struct sockaddr*", addr4), addrlen)
    local port = ffi.C.ntohs(addr4.sin_port)
    local cli = socket.tcp()
    cli:settimeout(0.5)
    pcall(function()
      return cli:connect("127.0.0.1", port)
    end)
    local ready, _ = socket.socket_select({
      srv
    }, nil, 0.5)
    assert.equals(1, #ready)
    assert.equals(srv.fd, ready[1].fd)
    local c = srv:accept()
    if c then
      c:close()
    end
    cli:close()
    return srv:close()
  end)
end)
