return describe("worker_sip helpers", function()
  local worker_sip = require("worker_sip")
  describe("classify_direction", function()
    it("returns not-sip when neither side uses port 5060", function()
      local outbound, inbound, is_sip = worker_sip.classify_direction(4242, 4243, "10.35.1.2", "10.35.1.3")
      assert.is_false(outbound)
      assert.is_false(inbound)
      return assert.is_false(is_sip)
    end)
    it("classifies outbound request to 5060", function()
      local outbound, inbound, is_sip = worker_sip.classify_direction(5072, 5060, "10.35.3.6", "83.136.161.35")
      assert.is_true(outbound)
      assert.is_false(inbound)
      return assert.is_true(is_sip)
    end)
    return it("classifies inbound when destination is a known phone even with random source port", function()
      worker_sip.remember_phone_ip("10.35.3.6", "48:25:67:f7:96:52")
      local outbound, inbound, is_sip = worker_sip.classify_direction(49832, 5060, "83.136.161.35", "10.35.3.6")
      assert.is_false(outbound)
      assert.is_true(inbound)
      return assert.is_true(is_sip)
    end)
  end)
  return describe("resolve_outbound_mac", function()
    it("prefers cached phone MAC over packet MAC", function()
      worker_sip.remember_phone_ip("10.35.3.6", "48:25:67:f7:96:52")
      local mac = worker_sip.resolve_outbound_mac("10.35.3.6", "58:d6:1f:57:4f:94")
      return assert.are.equal("48:25:67:f7:96:52", mac)
    end)
    it("falls back to packet MAC when cache is empty", function()
      local mac = worker_sip.resolve_outbound_mac("10.35.3.250", "48:25:67:f7:96:52")
      return assert.are.equal("48:25:67:f7:96:52", mac)
    end)
    return it("does not use packet MAC fallback for non-lan source IP", function()
      local mac = worker_sip.resolve_outbound_mac("83.136.164.102", "58:d6:1f:57:4f:94")
      return assert.is_nil(mac)
    end)
  end)
end)
