local create_cache
create_cache = require("auth.cert_cache").create_cache
local CERT = "-----BEGIN CERTIFICATE-----\ntest\n-----END CERTIFICATE-----"
local KEY = "-----BEGIN PRIVATE KEY-----\ntest\n-----END PRIVATE KEY-----"
return describe("auth/cert_cache", function()
  it("insert + get basique", function()
    local cache = create_cache(10, 3600, "tmp/test_certs_u1")
    cache.clear()
    assert.is_true(cache.set("example.com", CERT, KEY, nil))
    local entry = cache.get("example.com")
    assert.is_not_nil(entry)
    assert.equals(CERT, entry.cert_pem)
    return assert.equals(KEY, entry.key_pem)
  end)
  it("insensible à la casse", function()
    local cache = create_cache(10, 3600, "tmp/test_certs_u2")
    cache.clear()
    cache.set("Example.COM", "CERT", "KEY", nil)
    local entry = cache.get("example.com")
    assert.is_not_nil(entry)
    return assert.equals("CERT", entry.cert_pem)
  end)
  it("éviction LRU (max_size=3)", function()
    local cache = create_cache(3, 3600, "tmp/test_certs_u3")
    cache.clear()
    for i = 1, 4 do
      cache.set("host" .. tostring(i) .. ".com", "cert" .. tostring(i), "key" .. tostring(i), nil)
    end
    local s = cache.stats()
    return assert.equals(3, s.size_ram)
  end)
  it("persistance disque entre instances", function()
    local dir = "tmp/test_certs_u4"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    cache.set("persist.unit", "MYCERT", "MYKEY", nil)
    local cache2 = create_cache(10, 3600, dir)
    local entry = cache2.get("persist.unit")
    assert.is_not_nil(entry, "doit charger depuis disque")
    assert.equals("MYCERT", entry.cert_pem)
    return assert.equals("MYKEY", entry.key_pem)
  end)
  return it("get retourne nil si l'index indique expiration", function()
    local dir = "tmp/test_certs_u5"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    cache.set("expire.unit", "CERT", "KEY", nil)
    local idx_path = "tmp/cert_cache_index.lua"
    local fh = io.open(idx_path, "w")
    fh:write('return { ["expire.unit"] = { expires_at=1, accessed_at=1 } }\n')
    fh:close()
    local cache2 = create_cache(10, 3600, dir)
    return assert.is_nil(cache2.get("expire.unit"))
  end)
end)
