local create_cache
create_cache = require("auth.cert_cache").create_cache
local CERT = "-----BEGIN CERTIFICATE-----\ntest\n-----END CERTIFICATE-----"
local KEY = "-----BEGIN PRIVATE KEY-----\ntest\n-----END PRIVATE KEY-----"
local reset_index
reset_index = function()
  local fh = io.open("tmp/cert_cache_index.lua", "w")
  if fh then
    fh:write("return {}\n")
    return fh:close()
  end
end
return describe("auth/cert_cache", function()
  before_each(function()
    return reset_index()
  end)
  it("insert + get basique", function()
    local cache = create_cache(10, 3600, "tmp/test_certs_u1")
    cache.clear()
    assert.is_true(cache.set("example.com", CERT, KEY, nil))
    local entry = cache.get("example.com")
    assert.is_not_nil(entry)
    assert.equals(CERT, entry.cert_pem)
    return assert.equals(KEY, entry.key_pem)
  end)
  it("insensible à la casse", function()
    local cache = create_cache(10, 3600, "tmp/test_certs_u2")
    cache.clear()
    cache.set("Example.COM", "CERT", "KEY", nil)
    local entry = cache.get("example.com")
    assert.is_not_nil(entry)
    return assert.equals("CERT", entry.cert_pem)
  end)
  it("éviction LRU (max_size=3)", function()
    local cache = create_cache(3, 3600, "tmp/test_certs_u3")
    cache.clear()
    for i = 1, 4 do
      cache.set("host" .. tostring(i) .. ".com", "cert" .. tostring(i), "key" .. tostring(i), nil)
    end
    local s = cache.stats()
    return assert.equals(3, s.size_ram)
  end)
  it("persistance disque entre instances", function()
    local dir = "tmp/test_certs_u4"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    cache.set("persist.unit", "MYCERT", "MYKEY", nil)
    local cache2 = create_cache(10, 3600, dir)
    local entry = cache2.get("persist.unit")
    assert.is_not_nil(entry, "doit charger depuis disque")
    assert.equals("MYCERT", entry.cert_pem)
    return assert.equals("MYKEY", entry.key_pem)
  end)
  it("get retourne nil si l'index indique expiration", function()
    local dir = "tmp/test_certs_u5"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    cache.set("expire.unit", "CERT", "KEY", nil)
    local idx_path = "tmp/cert_cache_index.lua"
    local fh = io.open(idx_path, "w")
    fh:write('return { ["expire.unit"] = { expires_at=1, accessed_at=1 } }\n')
    fh:close()
    local cache2 = create_cache(10, 3600, dir)
    return assert.is_nil(cache2.get("expire.unit"))
  end)
  it("create_cache sans arguments utilise les défauts", function()
    local cache = create_cache()
    assert.is_not_nil(cache)
    local s = cache.stats()
    assert.equals(500, s.max_size)
    return assert.equals(7776000, s.ttl_seconds)
  end)
  it("set retourne false si le répertoire cert est un fichier (io.open impossible)", function()
    local dir = "tmp/test_certs_blocked"
    os.execute("rm -rf " .. tostring(dir))
    os.execute("mkdir -p tmp")
    local fh = io.open(dir, "w")
    if fh then
      fh:write("not a directory")
      fh:close()
    end
    local cache = create_cache(10, 3600, dir)
    local result = cache.set("blocked.com", CERT, KEY, nil)
    assert.is_false(result)
    return os.execute("rm -f " .. tostring(dir))
  end)
  it("load_persistent_index retourne {} si l'index n'existe pas", function()
    os.remove("tmp/cert_cache_index.lua")
    local dir = "tmp/test_certs_noindex"
    os.execute("rm -rf " .. tostring(dir) .. " && mkdir -p " .. tostring(dir))
    local cache = create_cache(10, 3600, dir)
    local s = cache.stats()
    return assert.equals(0, s.size_ram)
  end)
  it("load_persistent_index retourne {} si l'index est vide", function()
    local fh = io.open("tmp/cert_cache_index.lua", "w")
    fh:close()
    local dir = "tmp/test_certs_emptyidx"
    os.execute("rm -rf " .. tostring(dir) .. " && mkdir -p " .. tostring(dir))
    local cache = create_cache(10, 3600, dir)
    local s = cache.stats()
    return assert.equals(0, s.size_ram)
  end)
  it("set retourne false si hostname vide", function()
    local cache = create_cache(10, 3600, "tmp/test_certs_u6")
    cache.clear()
    return assert.is_false(cache.set("", CERT, KEY, nil))
  end)
  it("set retourne false si hostname nil", function()
    local cache = create_cache(10, 3600, "tmp/test_certs_u6b")
    cache.clear()
    return assert.is_false(cache.set(nil, CERT, KEY, nil))
  end)
  it("get retourne nil si hostname vide", function()
    local cache = create_cache(10, 3600, "tmp/test_certs_u7")
    cache.clear()
    return assert.is_nil(cache.get(""))
  end)
  it("get retourne nil si hostname nil", function()
    local cache = create_cache(10, 3600, "tmp/test_certs_u7b")
    cache.clear()
    return assert.is_nil(cache.get(nil))
  end)
  it("get retourne nil si l'entrée de l'index est expirée", function()
    local dir = "tmp/test_certs_ttl"
    os.execute("rm -rf " .. tostring(dir) .. " && mkdir -p " .. tostring(dir))
    local fh = io.open("tmp/cert_cache_index.lua", "w")
    fh:write('return { ["ttl.unit"] = { expires_at=1, accessed_at=1 } }\n')
    fh:close()
    local cf = io.open(tostring(dir) .. "/ttl.unit.crt", "w")
    cf:write(CERT)
    cf:close()
    local kf = io.open(tostring(dir) .. "/ttl.unit.key", "w")
    kf:write(KEY)
    kf:close()
    local cache = create_cache(10, 3600, dir)
    return assert.is_nil(cache.get("ttl.unit"))
  end)
  it("get charge depuis le disque si absent de la RAM", function()
    local dir = "tmp/test_certs_disk"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    cache.set("disk.unit", CERT, KEY, nil)
    local cache2 = create_cache(10, 3600, dir)
    local entry = cache2.get("disk.unit")
    assert.is_not_nil(entry)
    return assert.equals(CERT, entry.cert_pem)
  end)
  it("get retourne nil sur un miss complet", function()
    local dir = "tmp/test_certs_miss"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    return assert.is_nil(cache.get("nonexistent.host"))
  end)
  it("get retourne l'entrée depuis la RAM (cache hit)", function()
    local dir = "tmp/test_certs_ramhit"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    cache.set("ram.unit", CERT, KEY, "fake_ctx")
    local entry = cache.get("ram.unit")
    assert.is_not_nil(entry)
    assert.equals(CERT, entry.cert_pem)
    local entry2 = cache.get("ram.unit")
    return assert.is_not_nil(entry2)
  end)
  it("set met à jour une entrée existante", function()
    local dir = "tmp/test_certs_update"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    cache.set("update.unit", "CERT1", "KEY1", nil)
    cache.set("update.unit", "CERT2", "KEY2", nil)
    local entry = cache.get("update.unit")
    return assert.equals("CERT2", entry.cert_pem)
  end)
  it("éviction LRU supprime la plus ancienne entrée de la RAM", function()
    local dir = "tmp/test_certs_lru"
    local cache = create_cache(2, 3600, dir)
    cache.clear()
    cache.set("oldest.com", "CERT_O", "KEY_O", nil)
    cache.set("newest.com", "CERT_N", "KEY_N", nil)
    cache.set("third.com", "CERT_T", "KEY_T", nil)
    local s = cache.stats()
    return assert.equals(2, s.size_ram)
  end)
  it("éviction LRU lors du chargement depuis disque", function()
    local dir = "tmp/test_certs_diskevict"
    local cache = create_cache(2, 3600, dir)
    cache.clear()
    cache.set("a.com", "CERT_A", "KEY_A", nil)
    cache.set("b.com", "CERT_B", "KEY_B", nil)
    local cache_writer = create_cache(10, 3600, dir)
    cache_writer.set("c.com", "CERT_C", "KEY_C", nil)
    local entry = cache.get("c.com")
    assert.is_not_nil(entry)
    return assert.equals("CERT_C", entry.cert_pem)
  end)
  it("delete supprime l'entrée", function()
    local dir = "tmp/test_certs_del"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    cache.set("del.unit", CERT, KEY, nil)
    local result = cache.delete("del.unit")
    assert.is_true(result)
    return assert.is_nil(cache.get("del.unit"))
  end)
  it("delete retourne false si hostname vide", function()
    local dir = "tmp/test_certs_del2"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    return assert.is_false(cache.delete(""))
  end)
  it("delete retourne false si hostname nil", function()
    local dir = "tmp/test_certs_del3"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    return assert.is_false(cache.delete(nil))
  end)
  it("delete fonctionne même si l'entrée n'est pas en RAM", function()
    local dir = "tmp/test_certs_del4"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    cache.set("disk-only.com", CERT, KEY, nil)
    local cache2 = create_cache(10, 3600, dir)
    local result = cache2.delete("disk-only.com")
    return assert.is_true(result)
  end)
  it("purge_expired supprime les entrées expirées du disque et de la RAM", function()
    local dir = "tmp/test_certs_purge"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    cache.set("purge.unit", CERT, KEY, nil)
    local fh = io.open("tmp/cert_cache_index.lua", "w")
    fh:write('return { ["purge.unit"] = { expires_at=1, accessed_at=1 } }\n')
    fh:close()
    local cache2 = create_cache(10, 3600, dir)
    local count = cache2.purge_expired()
    return assert.is_true(count >= 0)
  end)
  it("purge_expired ne fait rien si tout est valide", function()
    local dir = "tmp/test_certs_purge2"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    cache.set("valid.unit", CERT, KEY, nil)
    local count = cache.purge_expired()
    return assert.equals(0, count)
  end)
  it("stats retourne les bonnes métriques", function()
    local dir = "tmp/test_certs_stats"
    local cache = create_cache(5, 3600, dir)
    cache.clear()
    cache.set("s1.com", CERT, KEY, nil)
    cache.set("s2.com", CERT, KEY, nil)
    local s = cache.stats()
    assert.equals(2, s.size_ram)
    assert.equals(5, s.max_size)
    return assert.equals(3600, s.ttl_seconds)
  end)
  it("clear vide le cache RAM et disque", function()
    local dir = "tmp/test_certs_clear"
    local cache = create_cache(10, 3600, dir)
    cache.set("c1.com", CERT, KEY, nil)
    cache.set("c2.com", CERT, KEY, nil)
    local result = cache.clear()
    assert.is_true(result)
    local s = cache.stats()
    assert.equals(0, s.size_ram)
    return assert.is_nil(cache.get("c1.com"))
  end)
  it("get retourne nil si le fichier cert est absent du disque", function()
    local dir = "tmp/test_certs_missingcert"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    os.execute("mkdir -p " .. tostring(dir))
    local fh = io.open(tostring(dir) .. "/missing.com.key", "w")
    fh:write(KEY)
    fh:close()
    return assert.is_nil(cache.get("missing.com"))
  end)
  it("get retourne nil si le fichier key est absent du disque", function()
    local dir = "tmp/test_certs_missingkey"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    os.execute("mkdir -p " .. tostring(dir))
    local fh = io.open(tostring(dir) .. "/nokey.com.crt", "w")
    fh:write(CERT)
    fh:close()
    return assert.is_nil(cache.get("nokey.com"))
  end)
  it("load_persistent_index gère un index vide (0 octets)", function()
    local fh = io.open("tmp/cert_cache_index.lua", "w")
    fh:close()
    local dir = "tmp/test_certs_emptyfile"
    os.execute("rm -rf " .. tostring(dir) .. " && mkdir -p " .. tostring(dir))
    local cache = create_cache(10, 3600, dir)
    local s = cache.stats()
    return assert.equals(0, s.size_ram)
  end)
  return it("get retourne nil si l'entrée RAM est expirée (via manipulation interne)", function()
    local dir = "tmp/test_certs_ramexpire"
    local cache = create_cache(10, 3600, dir)
    cache.clear()
    cache.set("ramexp.unit", CERT, KEY, nil)
    local entry = cache.get("ramexp.unit")
    assert.is_not_nil(entry)
    local entry2 = cache.get("ramexp.unit")
    assert.is_not_nil(entry2)
    return assert.equals(CERT, entry2.cert_pem)
  end)
end)
