return describe("auth.user_sessions", function()
  local init, add_session, get_session, is_authenticated, refresh_session, remove_session, cleanup_expired, get_all_sessions
  do
    local _obj_0 = require("auth.user_sessions")
    init, add_session, get_session, is_authenticated, refresh_session, remove_session, cleanup_expired, get_all_sessions = _obj_0.init, _obj_0.add_session, _obj_0.get_session, _obj_0.is_authenticated, _obj_0.refresh_session, _obj_0.remove_session, _obj_0.cleanup_expired, _obj_0.get_all_sessions
  end
  before_each(function()
    return init(3600)
  end)
  describe("add_session", function()
    it("adds a new user session", function()
      local result = add_session("alice", "192.168.1.10", "aa:bb:cc:dd:ee:ff")
      return assert.is_true(result)
    end)
    it("returns false for missing username", function()
      local result = add_session(nil, "192.168.1.10", "aa:bb:cc:dd:ee:ff")
      return assert.is_false(result)
    end)
    it("returns false for missing IP", function()
      local result = add_session("alice", nil, "aa:bb:cc:dd:ee:ff")
      return assert.is_false(result)
    end)
    return it("returns false for missing MAC", function()
      local result = add_session("alice", "192.168.1.10", nil)
      return assert.is_false(result)
    end)
  end)
  describe("get_session", function()
    it("retrieves an added session", function()
      add_session("alice", "192.168.1.10", "aa:bb:cc:dd:ee:ff")
      local session = get_session("alice")
      assert.is_not_nil(session)
      assert.equals("alice", session.username)
      assert.equals("192.168.1.10", session.src_ip)
      return assert.equals("aa:bb:cc:dd:ee:ff", session.mac)
    end)
    it("returns nil for non-existent session", function()
      local session = get_session("nonexistent")
      return assert.is_nil(session)
    end)
    return it("case-insensitive username lookup", function()
      add_session("Alice", "192.168.1.10", "aa:bb:cc:dd:ee:ff")
      local session = get_session("ALICE")
      assert.is_not_nil(session)
      return assert.equals("alice", session.username)
    end)
  end)
  describe("is_authenticated", function()
    it("returns true for authenticated user", function()
      add_session("alice", "192.168.1.10", "aa:bb:cc:dd:ee:ff")
      local result = is_authenticated("alice")
      return assert.is_true(result)
    end)
    it("returns false for unauthenticated user", function()
      local result = is_authenticated("bob")
      return assert.is_false(result)
    end)
    it("validates IP if provided", function()
      add_session("alice", "192.168.1.10", "aa:bb:cc:dd:ee:ff")
      local result = is_authenticated("alice", "192.168.1.10")
      assert.is_true(result)
      result = is_authenticated("alice", "192.168.1.20")
      return assert.is_false(result)
    end)
    return it("validates MAC if provided", function()
      add_session("alice", "192.168.1.10", "aa:bb:cc:dd:ee:ff")
      local result = is_authenticated("alice", nil, "aa:bb:cc:dd:ee:ff")
      assert.is_true(result)
      result = is_authenticated("alice", nil, "11:22:33:44:55:66")
      return assert.is_false(result)
    end)
  end)
  describe("refresh_session", function()
    it("extends session timeout", function()
      add_session("alice", "192.168.1.10", "aa:bb:cc:dd:ee:ff")
      local session1 = get_session("alice")
      local expires1 = session1.expires
      os.execute("sleep 1")
      refresh_session("alice")
      local session2 = get_session("alice")
      local expires2 = session2.expires
      return assert.is_true(expires2 > expires1)
    end)
    return it("returns false for non-existent session", function()
      local result = refresh_session("nonexistent")
      return assert.is_false(result)
    end)
  end)
  describe("remove_session", function()
    it("removes an existing session", function()
      add_session("alice", "192.168.1.10", "aa:bb:cc:dd:ee:ff")
      assert.is_not_nil(get_session("alice"))
      local result = remove_session("alice")
      assert.is_true(result)
      return assert.is_nil(get_session("alice"))
    end)
    return it("returns false for non-existent session", function()
      local result = remove_session("nonexistent")
      return assert.is_false(result)
    end)
  end)
  describe("get_all_sessions", function()
    it("returns all active sessions", function()
      add_session("alice", "192.168.1.10", "aa:bb:cc:dd:ee:ff")
      add_session("bob", "192.168.1.20", "11:22:33:44:55:66")
      local all = get_all_sessions()
      local session_count = 0
      for k in pairs(all) do
        session_count = session_count + 1
      end
      assert.equals(2, session_count)
      assert.is_not_nil(all.alice)
      return assert.is_not_nil(all.bob)
    end)
    return it("returns empty table when no sessions", function()
      local all = get_all_sessions()
      local session_count = 0
      for k in pairs(all) do
        session_count = session_count + 1
      end
      return assert.equals(0, session_count)
    end)
  end)
  return describe("cleanup_expired", function()
    return it("removes expired sessions", function()
      init(0)
      add_session("alice", "192.168.1.10", "aa:bb:cc:dd:ee:ff")
      os.execute("sleep 1")
      local count = cleanup_expired()
      assert.equals(1, count)
      return assert.is_nil(get_session("alice"))
    end)
  end)
end)
